### ISSUE TITLE
CLIENTE SATELITE ASSISTENCIA - NAO GERA LOTE

### ISSUE THREAD

**Issue by Camila123** [JZResgate/NASA-Issues#100]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Fechamento / Atendimento / Histórico / Detalhes

- O que ocorreu?
Assistências deste cliente em especifico não geram lote. Ao clicar em "gerar lote", sistema fica só processando e em seguida aparece mensagem de erro.

- Numero do sinistro
*Ex: 2016016762

- Horário da solicitação
*23/01/2017 13:53 

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/25299834/22211195/71f61dc4-e173-11e6-9df0-bf6c1851cdd0.png)

![image](https://cloud.githubusercontent.com/assets/25299834/22211283/b86b2b5a-e173-11e6-9a46-d951bbbe9978.png)

**Comment by bhdebrito** [comment]
Por favor evitar abrir chamados duplicados.

Acompanhar o chamado #97

**Comment by Camila123** [comment]
SATELITE ASSISTENCIA, SERVIÇOS DE DEZEMBRO NAO GERAM LOTE
