### ISSUE TITLE
Erro para marcar como analisada

### ISSUE THREAD

**Issue by priscila123** [JZResgate/NASA-Issues#101]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?

Atendimento>>Histórico>>Detalhes

- O que ocorreu? 

Ao gerar lote do atendimento não é possível marcar o serviço como analisada.

- Numero do sinistro

WO0000002760484

- Horário da solicitação
13:55 hrs

- Print da tela

![image](https://cloud.githubusercontent.com/assets/25300406/22211279/b5f1096c-e173-11e6-9da0-fc4c403d4bcc.png)

**Comment by spmarco** [comment]
Corrigido
