### ISSUE TITLE
cliente land motors - nao gera lote

### ISSUE THREAD

**Issue by Camila123** [JZResgate/NASA-Issues#102]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Atendimento / Historico / Detalhes 
- O que ocorreu?
Assistencia do cliente LAND MOTORS nao gera lote. Ao clicarmos em "gerar lote", sistema fica processando e em seguida aparece mensagem de erro.

- Numero do sinistro
*Ex: JZ2017116101254

- Horário da solicitação
*23/01/2017 14:00

- Print da tela
![image](https://cloud.githubusercontent.com/assets/25299834/22211522/690c8fd0-e174-11e6-80fc-8c30fbb87e20.png)

![image](https://cloud.githubusercontent.com/assets/25299834/22211537/73538cfa-e174-11e6-87e4-85f969931601.png)

**Comment by spmarco** [comment]
Fizemos umas correções no sistema, teste novamente

**Comment by bhdebrito** [comment]
Fechado sem resposta do usuario

**Comment by Camila123** [comment]
Ainda nao esta gerando lote.

**Comment by JZWillian** [comment]
boa tarde continua com o mesmo problema.

**Comment by JZWillian** [comment]
não consigo gerar lote dos clientes Land Motors e Satellite Assistencia
