### ISSUE TITLE
ATENDIMENTOS DA EUROP - MARCAR COMO ANALISADA

### ISSUE THREAD

**Issue by priscila123** [JZResgate/NASA-Issues#103]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?

**Atendimento>>Histórico>>Detalhes**

- O que ocorreu?

**Nos atendimentos da EA não estamos conseguindo marcar como analisada, mas o procedimento para esta cia é somente marcar como analisada pois quem faz o lançamento na página deles é o ROBO. 
Como devemos proceder neste caso, já que a estamos fazendo a análise mas sem marcar como tal.
precisamos madar NF o quanto antes.
Neste meio tempo devemos fazer o tramite manualmente para não perder tempo depois.**

- Numero do sinistro
***TODOS ATENDIMENTOS DA CIA EUROP**

- Horário da solicitação

 **15:20 (MAS ESTAMOS COM PROBLEMAS DESDE O DIA 19/01/2017**

- Print da tela

![image](https://cloud.githubusercontent.com/assets/25300406/22214668/a63d08a2-e17f-11e6-9daf-341cd24f97f6.png)

**Comment by spmarco** [comment]
Corrigido
