### ISSUE TITLE
MENU DE PAINEIS LATERAL SUMIU

### ISSUE THREAD

**Issue by JZMARRUDA** [JZResgate/NASA-Issues#104]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de atendimento.

- O que ocorreu?
O Menu de painéis da tela lateral sumiu, não consta mais na pagina de acesso, não conseguimos alterar entre as paginas do menu.

- Numero do sinistro
Não se aplica.

- Horário da solicitação
16:15

- Print da tela
A IMAGEM NÃO É SUPORTADA PELO SISTEMA.

**Comment by bhdebrito** [comment]
O menu esta carregando. Devido a lentidao apresentada esta demorando mais que o normal. 

Apenas aguarde carregar.

**Comment by bhdebrito** [comment]
Resolvido
