### ISSUE TITLE
Erro de serviços agendado 

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#106]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Serviço com Horário agendado para dia 24/01 e não esta caindo para acionamento e não conseguimos alterar agendamento

- Numero do sinistro
*Ex: 31624078

- Horário da solicitação
* 15:35hs

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

Não estamos conseguindo incluir print

**Comment by spmarco** [comment]
O erro continua?

**Comment by Maramoret** [comment]
Estamos com alguns casos que o serviços estava agendado, porém não caiu
para pendencia de acionamento.

006383 - Inter partner
8806131996 - MAPFRE



*Mara Silva*
Atendimento
Tel: (11) 2344-7138
*JZ Remoções *| http://www.jzresgate.com.br​
*​Agilidade, Inovação e Eficiência em Transportes*

2017-01-26 14:50 GMT-02:00 spmarco <notifications@github.com>:

**Comment by spmarco** [comment]
Vamos acompanhar, por causa destas instabilidades que deu o serviço responsável por trocar os status dos serviços e tirar os serviços de agendado para pendente de acionamento ficou fora por um tempo, talvez seja este o problema.
