### ISSUE TITLE
ACESSO NASA - DANILO ROLIM

### ISSUE THREAD

**Issue by Camila123** [JZResgate/NASA-Issues#107]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Acesso - Danilo Rolim

- O que ocorreu?
Esta sem acesso. Desde terça feira 24/01. 
Danilo esta usando o meu acesso "Camila Ramos".

- Numero do sinistro

- Horário da solicitação
26/01/2017 09:05

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/25299834/22329132/f870e39a-e3a6-11e6-8cd4-a74c96e387bd.png)

**Comment by spmarco** [comment]
Corrigido, ele esta com as mesmas permissões que você camila
