### ISSUE TITLE
Login - Nome de usuário 

### ISSUE THREAD

**Issue by priscila123** [JZResgate/NASA-Issues#109]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de login

- O que ocorreu?

Ao sair do sistema, aparece o nome do Paiva para se desconectar, como se estivesse logado no usuário dele.
- Numero do sinistro
 **
- Horário da solicitação

26/01/2017 - 09:40

- Print da tela

*Tire print da tela utilizando a "Ferramenta de Captura" do Window
![image](https://cloud.githubusercontent.com/assets/25300406/22330066/7c2ef8b2-e3ab-11e6-80d7-d677a3e52bbd.png)
s

**Comment by spmarco** [comment]
corrigido
