### ISSUE TITLE
Usuario

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#110]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Perfil de Usuário 
- O que ocorreu?
* Ao visualizar o Perfil no lado esquerdo na tela (Visualizo como usario "Rafael Paiva" mesmo logando com o meu logam e senha 

- Numero do sinistro
*Utilizando sinistro 31609116

- Horário da solicitação
*09:42hs

- Print da tela
*
![image](https://cloud.githubusercontent.com/assets/24894704/22330137/d24e709c-e3ab-11e6-8b94-f2441bb3d97f.png)

**Comment by spmarco** [comment]
corrigido
