### ISSUE TITLE
lentidão - Escrever comentários nas assistencias

### ISSUE THREAD

**Issue by Camila123** [JZResgate/NASA-Issues#111]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Atendimento / Historico / Detalhes

- O que ocorreu?
*Lentidão ao registrar comentários nos atendimentos.  

- Numero do sinistro
*Ex: WO0000002582787

- Horário da solicitação
26 01 17 09:44
- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/25299834/22330165/fcd8b610-e3ab-11e6-9865-7b50a983690c.png)

**Comment by spmarco** [comment]
Corrigido
