### ISSUE TITLE
Não gera status NEG

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#112]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
* Tela de detalhes do atendimento

- O que ocorreu?
* Ticado o item km para marcar como staus negociação, ao clicar em gerar lote o sistema carrega ..carrega..carrega, e quando atualiza permanece sem lote.. Feito o processo por 4 vezes ..
OBS: se apenas gerar lote e aceita..mas se for marcaso com status  NEG não gera 
- Numero do sinistro
* 31613202

- Horário da solicitação
* Entre 12:05 hs e 12:13 hs 

- Print da tela
*
![image](https://cloud.githubusercontent.com/assets/24894704/22334252/31e41d76-e3c1-11e6-911c-2bc4c7bf5c64.png)

**Comment by spmarco** [comment]
por causa da instabilidade afetou esta funcionalidade também. Faça novamente, provavelmente deve funcionar

**Comment by bhdebrito** [comment]
Fechado sem resposta do usuario
