### ISSUE TITLE
Não visualizo as informações 

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#113]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
* Tela detalhe de atendimento 

- O que ocorreu?
*Ao clicar para visualizar os detalhes do atendimento da erro na pagina 
- Numero do sinistro
*31616627

- Horário da solicitação
* 16:47hs 

- Print da tela
*
![image](https://cloud.githubusercontent.com/assets/24894704/22345521/856ec768-e3e7-11e6-8c43-fba598d7a239.png)

**Comment by bhdebrito** [comment]
Problema resolvido
