### ISSUE TITLE
Pesquisa de sinistro - CAMPO (O QUE VOCÊ DESEJA?)

### ISSUE THREAD

**Issue by priscila123** [JZResgate/NASA-Issues#114]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?

Tela: HISTÓRICO > ATENDIMENTO

- O que ocorreu?

AO PESQUISAR O SINITRO O SISTEMA FICA PEQUISANDO..... E DEPOIS CAI.

- Numero do sinistro

528429

- Horário da solicitação
26/01/2017 - 17:04

- Print da tela

![image](https://cloud.githubusercontent.com/assets/25300406/22345930/4b084d9a-e3e9-11e6-978f-f3898ea90c70.png)

**Comment by bhdebrito** [comment]
Sistema estava apresentando lentidao como um todo, peço que por favor se atente a estes sinais para nao lotar a fila de chamados com problemas semelhante.
