### ISSUE TITLE
Pesquisa  por periodo

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#115]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex:  Historico, 

- O que ocorreu?
*Ao pesquisar um periodo Mondial , da erro no NASA 

- Numero do sinistro
*Pesquisa  Cliente mondial entre 23/01/2017 e 23/01/2017

- Horário da solicitação
*26/01/2017 17:00 e 17:05 

- Print da tela
*
![image](https://cloud.githubusercontent.com/assets/24894704/22346018/7f49bf8a-e3e9-11e6-9fc2-1edbb89a588c.png)

![image](https://cloud.githubusercontent.com/assets/24894704/22346059/a9a9a2ae-e3e9-11e6-871f-e312ee608a03.png)

**Comment by bhdebrito** [comment]
Problema já relatado pela @priscila123 em #114 

Por favor, antes de abrir um chamado verifique se outro semelhante já nao esta na fila
