### ISSUE TITLE
Pesquisa de serviços - Histórico

### ISSUE THREAD

**Issue by priscila123** [JZResgate/NASA-Issues#116]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?

Tela de Histórico 

- O que ocorreu?

Ao pesquisar um período dos clientes, fica somente carregando.

- Numero do sinistro 

Período pesquisado

- Horário da solicitação

27/01/2017 - 08:14

- Print da tela

*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/25300406/22367434/b1261038-e468-11e6-99b6-c42a962b297b.png)

**Comment by spmarco** [comment]
Incompleto
