### ISSUE TITLE
HISTÓRICO - NAO ESTA PESQUISANDO

### ISSUE THREAD

**Issue by Camila123** [JZResgate/NASA-Issues#117]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Atendimento / Histórico Atendimento

- O que ocorreu?
Não estamos conseguindo realizar pesquisa através do do histórico.

- Numero do sinistro
*Ex: placa AVM-1562

- Horário da solicitação
27/01/2017 08:16

- Print da tela
![image](https://cloud.githubusercontent.com/assets/25299834/22367499/05fd0f62-e469-11e6-9e5f-e50f142f4651.png)

**Comment by bhdebrito** [comment]
Já está ok.
