### ISSUE TITLE
NASA CRISTIANE - NÃO ABRE

### ISSUE THREAD

**Issue by priscila123** [JZResgate/NASA-Issues#118]
O NASA DA CRISTIANE NÃO ABRE. 
ESTÁ CONFORME A IMAGEM ABAIXO:

![image](https://cloud.githubusercontent.com/assets/25300406/22430261/d37f9620-e6f4-11e6-9545-0246ebc7bca0.png)

**Comment by spmarco** [comment]
Corrigido
