### ISSUE TITLE
NASA DOS ANALISTAS FECHAMENTO 

### ISSUE THREAD

**Issue by priscila123** [JZResgate/NASA-Issues#120]
O NASA DE TODOS ANALISTAS NÃO ABRE COM O LINK  ENCAMINHADO VIA SPARK PELO MARCO.
A PÁGINA ABRE CONFORME IMAGEM ABAIXO:
![image](https://cloud.githubusercontent.com/assets/25300406/22431928/64e8fa34-e6fa-11e6-85aa-414d2851dc25.png)

**Comment by spmarco** [comment]
Corrigido
