### ISSUE TITLE
Erro NASA

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#121]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Erro NASA

- O que ocorreu?
* Ao pesquisar, atualizar , gerar lote, carrega ..carrega e da erro na pagina

- Numero do sinistro
*31654790

- Horário da solicitação
*15:44

- Print da tela
*
![image](https://cloud.githubusercontent.com/assets/24894704/22434402/071570a0-e703-11e6-8678-5a4dd2fe74d7.png)

**Comment by spmarco** [comment]
Instabilidade no site, estamos corrigindo
