### ISSUE TITLE
NASA não atualiza .

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#122]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
* Tela de atendimento, Historico

- O que ocorreu?
*Ao Tentar abrir o atendimento, ou gerar lote, alterar valores, carrega..carrega e depois aparece erro na pagina 

- Numero do sinistro
*31652622

- Horário da solicitação
*16:32

- Print da tela
*
![image](https://cloud.githubusercontent.com/assets/24894704/22436064/ab87d19a-e709-11e6-8af1-5c2dec19aa9c.png)

![image](https://cloud.githubusercontent.com/assets/24894704/22436081/b5f7db98-e709-11e6-86bd-3b68c45dfda1.png)

**Comment by spmarco** [comment]
Instabilidade no site, estamos corrigindo
