### ISSUE TITLE
NÃO ESTÁ EXPORTANDO 

### ISSUE THREAD

**Issue by Joelsonrodrigues** [JZResgate/NASA-Issues#124]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?Tela de atendimento,

- O que ocorreu?
Após capturar o serviço, e clicar na opção incluir para exportar, o mesmo fica carregando e não salva.

- Numero do sinistro
545876

- Horário da solicitação
31/01/2017 07:46

- Print da tela

![Uploading image.png…]()

**Comment by bhdebrito** [comment]
Chamado duplicado.

Acompanhe pelo #23
