### ISSUE TITLE
NASA travado 

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#125]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
* Tela de atendimento, Historico 
- O que ocorreu?
*Ao pesquisar, só carrega
*31391066

- Horário da solicitação
* 3101/2017 09:00hs

- Print da tela
*
![image](https://cloud.githubusercontent.com/assets/24894704/22462253/b4715288-e793-11e6-9c1b-bb7a3f2036f9.png)

**Comment by spmarco** [comment]
Estamos verificando
