### ISSUE TITLE
FALHA NA CAPTURA AUTOMÁTICA DO SERVIÇOS DA MONDIAL.

### ISSUE THREAD

**Issue by JZMARRUDA** [JZResgate/NASA-Issues#127]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
"Capturar".

- O que ocorreu?
O Sistema não está capturando automático os serviços da pagina da Mondial Assistance, sendo necessário estar exportando manual.

- Numero do sinistro
31676872, 31676921, 31676850, 31676867

- Horário da solicitação
19:00

- Print da tela
Não é possivel exemplificar com um print.

**Comment by bhdebrito** [comment]
Provavelmente alguma indisponibilidade temporária no WS deles. Já está normalizado.
