### ISSUE TITLE
Duplicidade

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#128]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Historico de atendimento e detalhe de Historico

- O que ocorreu?
*Consta lançado o mesmo sinistro 2 vezes, um deles esta com a placa incompleta e cancelado em zero no NASA , ao tentar abrir o atendimento correto para analise e finalização, o sistema abre apenas a saida que esta cancelada em zero..

- Numero do sinistro
*31671899

- Horário da solicitação
* 01/02/2017 15:14hs 

- Print da tela
*
![image](https://cloud.githubusercontent.com/assets/24894704/22517839/a35d5b1e-e891-11e6-91dc-7b929a6d3fbc.png)

![image](https://cloud.githubusercontent.com/assets/24894704/22517861/b5aa7de2-e891-11e6-82c9-1e92d7eba794.png)

**Comment by bhdebrito** [comment]
Resolvido, tente novamente.
