### ISSUE TITLE
Cadastro de novo prestador com problemas ao abrir a tela.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#129]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Agregado/Cadastrar

- O que ocorreu?
Quando clicamos em Prestado - Novo para cadastrarmos um novo prestador a tela abre com erro. 

- Horário da solicitação
15:30 hs 
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
Captura de Tela 2017-02-01 às 15.35.11
![image](https://cloud.githubusercontent.com/assets/23721255/22518566/3328f576-e894-11e6-9ab8-5a9304cf54b1.png)

![image](https://cloud.githubusercontent.com/assets/23721255/22518539/15734626-e894-11e6-9794-df049f2454cd.png)

**Comment by bhdebrito** [comment]
Resolvido
