### ISSUE TITLE
NASA - Esta com lentidão e com erro 

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#130]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
* Tela de atendimento, Historico, 

- O que ocorreu?
*Esta com lentião , ao pesquisar, marcar como analisado ou ao gerar lote 

- Numero do sinistro
*31561948

- Horário da solicitação
* 01/02/2017 16:26 

- Print da tela
*
![image](https://cloud.githubusercontent.com/assets/24894704/22520365/2b8954bc-e89b-11e6-879c-c5e014b3bf29.png)

![image](https://cloud.githubusercontent.com/assets/24894704/22520378/37080220-e89b-11e6-9476-5202da4fadb6.png)

**Comment by bhdebrito** [comment]
Já há um chamado aberto por voce sobre esse problema, por favor acompanhe o chamado #125
