### ISSUE TITLE
NASA COM PROBLEMAS

### ISSUE THREAD

**Issue by priscila123** [JZResgate/NASA-Issues#132]
O sistema está apresentando os seguintes erros:

A principio só carrega.
![image](https://cloud.githubusercontent.com/assets/25300406/22546386/0496d972-e924-11e6-9fbb-2b0bd5cb4f20.png)

E depois dá erro.

**Comment by bhdebrito** [comment]
Já há um chamade em aberto. #125 

Por favor, antes de abrir novos chamado, verifique se há problemas relacionado ao seu já em aberto.
