### ISSUE TITLE
PROBLEMAS HISTORICO NASA

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#133]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento,

- O que ocorreu?
*Não estamos conseguindo buscar nenhuma informação pelo Historico

- Numero do sinistro
*Ex: WO0000002819680

- Horário da solicitação
*13:30hs

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by bhdebrito** [comment]
#125

**Comment by spmarco** [comment]
No histórico só se pesquisa atendimentos que foram concluídos de alguma forma, **concluido, cancelado, cancelado em zero** e o servico WO0000002819680 ele ainda esta em andamento conforme print.
Caso você queira ver os detalhes vc pode clicar no botão azul marcado com a seta

![image](https://cloud.githubusercontent.com/assets/10270935/22559003/7a4556e2-e94e-11e6-8903-0c41d8ac0d0b.png)

**Comment by Maramoret** [comment]
Prezados,

Esse atendimento é uma segunda remoção, precisamos analisar a primeira que
foi cancelado na Saida.

Não estou conseguindo Visualizar no histórico.

[image: Imagem inline 1]

*Mara Silva*
Atendimento
Tel: (11) 2344-7138
*JZ Remoções *| http://www.jzresgate.com.br​
*​Agilidade, Inovação e Eficiência em Transportes*

Em 2 de fevereiro de 2017 14:50, spmarco <notifications@github.com>
escreveu:

**Comment by bhdebrito** [comment]
Os dois servicos estao aparecendo normalmente, qual a dificuldade que apresenta para voce?
![image](https://cloud.githubusercontent.com/assets/7241156/22559735/33d7137a-e959-11e6-8d9b-c594fa87b000.png)
![image](https://cloud.githubusercontent.com/assets/7241156/22559749/411a7f40-e959-11e6-897a-46371e44ec73.png)

**Comment by Maramoret** [comment]
A dificuldade é que no meu Nasa não estou conseguindo acessar o histórico e
visualizar o campo do financeiro.


[image: Imagem inline 1]

*Mara Silva*
Atendimento
Tel: (11) 2344-7138
*JZ Remoções *| http://www.jzresgate.com.br​
*​Agilidade, Inovação e Eficiência em Transportes*

2017-02-02 15:07 GMT-02:00 Bruno Brito <notifications@github.com>:

**Comment by spmarco** [comment]
Conforme te respondi é só clicar no botão azul com três pontinhos enquanto ele esta em atendimento.
Mas neste caso se você for consultar o serviço novamente ele vai aparecer porque o segundo foi concluido, só ir na tela de historico

**Comment by Maramoret** [comment]
Ok Obrigada.

Agora esta aparecendo.

[image: Imagem inline 1]

*Mara Silva*
Atendimento
Tel: (11) 2344-7138
*JZ Remoções *| http://www.jzresgate.com.br​
*​Agilidade, Inovação e Eficiência em Transportes*

Em 2 de fevereiro de 2017 15:37, spmarco <notifications@github.com>
escreveu:

**Comment by bhdebrito** [comment]
Estranho ter acontecido isso, não há modificações sistêmicas desde o dia 31/01
![image](https://cloud.githubusercontent.com/assets/7241156/22561228/7a315bb4-e95e-11e6-88d7-70079c77ea6d.png)
