### ISSUE TITLE
"gerar nova fatura" - Erro

### ISSUE THREAD

**Issue by Camila123** [JZResgate/NASA-Issues#134]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
* Financeiro: - Fatura / Pesquisa

- O que ocorreu?
*Não estamos conseguindo gerar "nova fatura". 
Ao clicarmos no botão "nova fatura", aparece uma mensagem de erro.

- Numero do sinistro

- Horário da solicitação
02/02/2017 16:57

- Print da tela
![image](https://cloud.githubusercontent.com/assets/25299834/22563678/c688aff8-e968-11e6-94d3-a93f52cefb8d.png)
![image](https://cloud.githubusercontent.com/assets/25299834/22563683/d0a2edfa-e968-11e6-825a-08d9ccd4b526.png)

**Comment by spmarco** [comment]
corrigido
