### ISSUE TITLE
Problema em verificar a rota do caminhão apos conclusão do atendimento.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#135]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Atendimento/Historico/Detalhes?id=542318&servico=1

- O que ocorreu?
Não estou conseguindo abrir a rota que o caminhão fez apos a conclusão do sistema.

- Numero do sinistro
542318

- Horário da solicitação

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/22588252/21816c96-e9ec-11e6-8d08-1866ebf356e3.png)

**Comment by bhdebrito** [comment]
Houve um problema na rotina de backup e nao temos os pontos desse atendimento. Terá que ser consultado através da Positron
