### ISSUE TITLE
Lentidão NASA

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#136]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Sistema com lentidão fica somente com status processando

- Numero do sinistro
*Ex: 

- Horário da solicitação
*09:33

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by bhdebrito** [comment]
Processando que tipo de solicitação? Qual sinistro?

O tempo de resposta médio hoje está em 330ms, abaixo de 1 segundo. Preciso que seja mais especifico sobre o que está lento.

**Comment by bhdebrito** [comment]
Sem resposta, redirecionado para o tópico #125
