### ISSUE TITLE
NASA TRAVADO

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#137]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASA  todas as telas

- O que ocorreu?
Lentidão e travamento do sistema

- Numero do sinistro
31703500

- Horário da solicitação
09:35

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by bhdebrito** [comment]
Chamado ja aberto, #136
