### ISSUE TITLE
Ordem do NASA invertido

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#138]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASA todas as telas

- O que ocorreu?
A ordem dos acionamentos estão invertidos, dificultando no acompanhamento

- Numero do sinistro

- Horário da solicitação
08:28

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by spmarco** [comment]
Ordenação restabelecida
