### ISSUE TITLE
Captura Mondial fora do AR

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#139]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Serviços não estão caindo na captura

- Numero do sinistro
*Ex: 31717576 e 31718218

- Horário da solicitação
*10:10

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by spmarco** [comment]
serviço restabelecido
