### ISSUE TITLE
[MELHORIA] EXCLUIR ITENS DE TABELA

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#140]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de inserção de valores 

- O que ocorreu?
Preciso que os itens de tabela sejam excluídas para que manualmente eu possa inserir corretamente os itens  / nesse caso do cliente UON CONSULTING

- Numero do sinistro

- Horário da solicitação
11:17

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by bhdebrito** [comment]
Existem rotinas do financeiro associados a tabela de valores, sem eles o sistema nao funciona corretamente. 

Por isso nao é possível remover os itens padrões.

**Comment by bhdebrito** [comment]
Proxima versao.
