### ISSUE TITLE
O LUAN NÃO ESTÁ MUDANDO AUTOMÁTICO OS STATUS DOS SERVIÇOS.

### ISSUE THREAD

**Issue by JZMARRUDA** [JZResgate/NASA-Issues#141]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Mudanças de Status

- O que ocorreu?
As frotas estão transitando entre endereço de origem e destino mas o status não está sendo alterado.

- Numero do sinistro
8806166579

- Horário da solicitação
15:40

- Print da tela
Os print'ws foram enviados por email, devido não estarmos conseguindo anexar.

**Comment by spmarco** [comment]
corrigido
