### ISSUE TITLE
Motorista aceita o serviço via aplicativo  a assistência  desvincula da frota 

### ISSUE THREAD

**Issue by alanoliveira158420** [JZResgate/NASA-Issues#142]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de Atendimento 

- O que ocorreu?
Quando o motorista aceita o serviço via aplicativo  a assistência  desvincula da frota 

- Numero do sinistro
JZ201726103550

- Horário da solicitação
16:19:00

- Print da tela

*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/23521390/22705091/4ca7e914-ed51-11e6-9637-ed5720207693.png) 

![image](https://cloud.githubusercontent.com/assets/23521390/22705102/5c3b4e3e-ed51-11e6-9c46-6313545c20d0.png)

**Comment by bhdebrito** [comment]
Será corrigido na próxima versao
