### ISSUE TITLE
CAPTURA EUROP

### ISSUE THREAD

**Issue by eliasreis** [JZResgate/NASA-Issues#144]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de atendimento

- O que ocorreu?
 Os serviços da EUROP não estão caindo no captura 

- Numero do sinistro
 WO0000002843853

- Horário da solicitação
Por volta das 10h50 os serviços da europ pararam de cair no captura.

- Print da tela

![captura fsm](https://cloud.githubusercontent.com/assets/23520575/22738341/2af9bfde-edee-11e6-8cae-057d36901fb9.JPG)

**Comment by eliasreis** [comment]
![capturas](https://cloud.githubusercontent.com/assets/23520575/22738432/94737900-edee-11e6-85f7-e09ad6920e1d.JPG)

**Comment by bhdebrito** [comment]
Esse sinistro foi capturado automaticamente as 10:57
