### ISSUE TITLE
Agendado travado sem cair para acionamento

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#145]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Serviços agendado, porém conseguimos visualizar somente no historico e não caiu para pendencia de acionamento

- Numero do sinistro
*Ex: 8806169433

- Horário da solicitação
*11:46hs

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

![image](https://cloud.githubusercontent.com/assets/23521482/22740192/e5052c7c-edf5-11e6-8925-28a97e241161.png)

![image](https://cloud.githubusercontent.com/assets/23521482/22740204/f6c3ba96-edf5-11e6-9240-85f0f83d3222.png)

**Comment by spmarco** [comment]
Corrigido

**Comment by bhdebrito** [comment]
#141
