### ISSUE TITLE
Luan não está funcionando

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#146]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Todas as telas do NASA

- O que ocorreu?
O LUAN não está funcionando, não estamos vendo quando chega ao local 

- Numero do sinistro
8806169476	

- Horário da solicitação
12:41

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by spmarco** [comment]
Corrigido

**Comment by bhdebrito** [comment]
#141
