### ISSUE TITLE
Frota GJZ 025 - travada

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#147]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASA - Tela de Frota

- O que ocorreu?
Frota GJZ 025 está travada em Pontinho

- Numero do sinistro
Não tenho

- Horário da solicitação
07:59

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by spmarco** [comment]
corrigido
