### ISSUE TITLE
ALTERAÇÃO DE STATUS DOS SERVIÇOS

### ISSUE THREAD

**Issue by JZMARRUDA** [JZResgate/NASA-Issues#148]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Mudanças de Status

- O que ocorreu?
O Guncho percorreu todo o percurso sem a alteração do status automática.

- Numero do sinistro
WO0000002852556

- Horário da solicitação
16:44

- Print da tela
![image](https://cloud.githubusercontent.com/assets/24321843/22839231/b9a0b144-efaf-11e6-9640-81de5370c5c5.png)

![image](https://cloud.githubusercontent.com/assets/24321843/22839249/c9144870-efaf-11e6-847f-e63b000b1d23.png)

**Comment by bhdebrito** [comment]
Já identificamos o problema.

Obrigado por relatar, na próxima versao nao ocorrera mais isso.
