### ISSUE TITLE
31319032- Erro Duplicidade item 1

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#149]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: T, Historico, Detalhes do atendimento

- O que ocorreu?
*Ao abrir o Atendimento ele aparece como 1 item duplicidade , porem neste caso são  2 itens 
- Numero do sinistro
*Ex: 31319032

- Horário da solicitação
*14/02/2017 as 10:11

- Print da tela
*
![image](https://cloud.githubusercontent.com/assets/24894704/22928539/1e6fd7bc-f29e-11e6-9c4a-22bceadb8e2a.png)

**Comment by brunohbrito** [comment]
@Cristianerangel Isso acontece raramente com alguns atendimentos por falha no sistema e não tem impacto algum para o financeiro.

**Comment by Cristianerangel** [comment]
@brunohbrito 
Tem impacto sim , pois tenho um serviço de R$ 90,00 que ja esta faturado, não é devido e esta poluindo o sistema 


![image](https://cloud.githubusercontent.com/assets/24894704/23276717/2a47369a-f9ea-11e6-96ea-d946f05ec13e.png)

**Comment by brunohbrito** [comment]
@Cristianerangel Qual o impacto? Alem do visual, claro.

Me parece tudo normal:

2 Servicos
![image](https://cloud.githubusercontent.com/assets/7241156/23277248/ea6f3098-f9eb-11e6-8558-7a20a8daad53.png)

2 Servicos
![image](https://cloud.githubusercontent.com/assets/7241156/23277279/ff99a21e-f9eb-11e6-8079-f11ee1c4683c.png)

A unica coisa é que eles dividiram a tela.

**Comment by Cristianerangel** [comment]
@brunohbrito 

Relatórios, Numeros , Controle

**Comment by brunohbrito** [comment]
Mas @Cristianerangel sao 2 servicos, a unica coisa é que eles apareceram os dois ao mesmo tempo.

Eles existem, se um deles nao é devido basta cancelar o valor!
