### ISSUE TITLE
VIATURAS NAO RECEBENDO ENDEREÇO

### ISSUE THREAD

**Issue by carloshenriqueama** [JZResgate/NASA-Issues#15]
VIATURA SALIC 17 INFORMA QUE ACEITOU SERVIÇO MAS SOMENTE APARECEU O BAIRRO PARA O MESMO

**Comment by bhdebrito** [comment]
@carloshenriqueama, obrigado pelo feedback.

Precisamos de mais algumas informações para poder testar e fazer alguma intervenção.

* Versão do Android ?
* Modelo do celular ?
* Usuário do Motorista (E-mail) ?
* Qual o sinistro do atendimento ?

Se tiver duvidas, acesse: [Como relatar um problema no App Jz](https://github.com/JZResgate/NASA-Issues/wiki/Como-relatar-um-problema-no-aplicativo-Jz-Resgate)

**Comment by bhdebrito** [comment]
Acompanhe pelo erro #24 e faça novos comentários lá

Obrigado
