### ISSUE TITLE
WO0000002869978 Atendimento Concluido e Chat não foi finalizado

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#150]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*O atendimento em questão foi aberto um chat do motorista com atendimento, porém o mesmo já foi finalizado e Chat continua em aberto

- Numero do sinistro
*Ex: WO0000002869978

- Horário da solicitação
*

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

![image](https://cloud.githubusercontent.com/assets/23521482/22985539/dc543a74-f38f-11e6-8173-535b867fc36c.png)

![image](https://cloud.githubusercontent.com/assets/23521482/22985591/02c6f002-f390-11e6-9993-a26db39fccfd.png)

**Comment by spmarco** [comment]
Corrigido
