### ISSUE TITLE
CLIENTE 	ASSIST ME Assistência Veicular - NÃO  ESTAGERA LOTE

### ISSUE THREAD

**Issue by Camila123** [JZResgate/NASA-Issues#151]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Atendimento Histórico Detalhes 874/1018

- O que ocorreu?
*NÃO ESTA GERANDO LOTE
- Numero do sinistro
874/1018

- Horário da solicitação
16/02/2017 16:20
- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/25299834/23034735/e6a0b0d2-f463-11e6-862e-574da2e69425.png)

**Comment by spmarco** [comment]
Corrigido
