### ISSUE TITLE
Relatório Por Status Financeiro

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#152]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Relatorio > Financeiro > Faturamento > Por Status 

- O que ocorreu?
*Valores demonstrados no relatório não batem com a real do sistema.

Me chamem para dar exemplos.

**Comment by spmarco** [comment]
Conforme conversamos não esta acontecendo mais
