### ISSUE TITLE
Erro ao gerar lote ds clientes Land Motors e Satelite Assistencia

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#153]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Fechamento > Atendimento > histórico > Detalhes

- O que ocorreu?
Ao clicar no botão Gerar Lote o mesmo gera erro

- Numero do sinistro
*Ex: 
JZ201726132732

- Horário da solicitação
*17/02/2017 as 15:21

![image](https://cloud.githubusercontent.com/assets/24438478/23075759/d1e412d0-f524-11e6-8c3b-4c28417861a4.png)

**Comment by spmarco** [comment]
corrigido
