### ISSUE TITLE
IMPEDIR DE CONCLUIR SEM SENHA OS CLIENTES MONDIAL E FACIL ASSIST

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#154]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Conclusão do atendimentos Facil Assist e Mondial Assistance sem senha dos itens: SAIDA, KM, HP, HT, ESTADIA, PEDAGIO, EQUIPAMENTO, ETC....

- O que ocorreu?
O Fechamento é obrigado a entrar em todos os atendimentos no nasa (mesmo sendo só saida) entrar na pagina de acionamento do cliente (Facil e Mondial) pegar a senha dos itens , incluir no sistema NASA e lançar na pagina de fechamento dos clientes. 

por favor me chamarem para maiores esclarecimentos.

![image](https://cloud.githubusercontent.com/assets/24438478/23076123/4ea64c1a-f526-11e6-9c09-820d10436c8b.png)

**Comment by brunohbrito** [comment]
@JZWillian uma modificação desta do ponto de vista sistêmico praticamente inviabiliza a manutenção e criação do clientes atuais e dos novos, assim como terá que modificar quase toda estrutura de categoria do lançamento, tendo impactos gigantescos em todo o Financeiro.

Tem certeza da solicitacao disto? 
Me parece que estamos diante de uma inflexibilidade / limitação dos sistemas Mondial e Facil que impactam nossa operação.

**Comment by brunohbrito** [comment]
E ainda tem que levar em consideração as vezes em que o motorista conclui o serviço, hoje o sistema não distingui entre um usuário Jz e um usuário Motorista, fazendo uma modificação dessas, acabaria aparecendo uma mensagem de erro para o motorista dizendo que a senha não foi preenchida.

**Comment by JZWillian** [comment]
Bruno, 
isso é uma sugestão, caso consiga de alguma forma fazer com que o nosso operacional siga esse procedimento não vejo necessidade dessa criação.
Solicitamos, pois a partir de março estaremos mudando alguns processos que geram retrabalhos para a equipe de fechamento, hoje esse é um dos mais quadrados.

**Comment by brunohbrito** [comment]
Entendo. Minha sugestao é criar um relatório com o nome do atendente que conclui e repassar.

**Comment by JZWillian** [comment]
Pode ser...
Podemos sentar com o Reynaldo e Mara, dividir essa responsabilidade com eles. 
podemos bater um papo em grupo para alinhar esses pontos?

**Comment by brunohbrito** [comment]
Acho que isso já foi definido, tanto que gerou a demanda #256.

Portanto estou encerrando esse assunto.
