### ISSUE TITLE
Historico não esta funcionando

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#155]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Não estamos conseguindo exportar esse serviços devido historico não localizar as assistência anteriores e quando vamos lançar manual aparece a mensagem que já existe.
- Numero do sinistro
*Ex: 564545

- Horário da solicitação
*17:48

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

![image](https://cloud.githubusercontent.com/assets/23521482/23184263/e40cf7b0-f85d-11e6-96c1-1259b85f933a.png)

![image](https://cloud.githubusercontent.com/assets/23521482/23184274/ed52860a-f85d-11e6-8276-448f70053466.png)

**Comment by brunohbrito** [comment]
O atendimento foi localizado sem problema algum:

Historico Operacao
![image](https://cloud.githubusercontent.com/assets/7241156/23212549/037cfacc-f8e6-11e6-963a-09cd2486aedf.png)

Historico Financeiro
![image](https://cloud.githubusercontent.com/assets/7241156/23212587/2cfc48e4-f8e6-11e6-9ea9-76acfb430f5e.png)
