### ISSUE TITLE
Atendimentos pendente para analise , porem já analisados e faturados  

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#156]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Fechamento >> Atendimento Geral >> 

- O que ocorreu?
*Ficam pendente para  analisar  alguns atendimentos mesmo que estejam com lote gerado.

- Numero do sinistro
*Ex: WO0000002771564

- Horário da solicitação
*Consta pendente para analise atendimento que já esta com lote gerado e faturado em nota.

sugestão:
Se atendimento estiver gerado lote em Nota apos x tempo (ex. 24 horas) sistema  marca como analisado automaticamente, pois não se trata de atendimento em aberto para abalise.

obs. devemos entender os pós e contras,

- Print da tela
obs. 

![image](https://cloud.githubusercontent.com/assets/24438478/23262712/6db7d658-f9ba-11e6-8af2-078608cac547.png)

![image](https://cloud.githubusercontent.com/assets/24438478/23262725/7d5d6c6c-f9ba-11e6-9a51-e8c8d7a319ad.png)

![image](https://cloud.githubusercontent.com/assets/24438478/23262732/898bb11a-f9ba-11e6-8593-7bc383bfa4df.png)

*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by brunohbrito** [comment]
@JZWillian Hj o sistema não faz esse vinculo. Apesar de estar em lote, ele nao marca como analisado.

Entendo o que você pede e se quiser podemos fazer, mas nao acha que isso pode potencilizar possiveis problemas? Afinal, um atendimento nao analisado pode ser posto como analisado erroneamente ao ser colocado no Lote.

**Comment by brunohbrito** [comment]
Ok, será colocado na fila para desenvolvimento

**Comment by JZWillian** [comment]
Você está entendendo errado.

 

Não estou mostrando um erro que eu esteja vendo e você não.

Estou informado um ocorrido que foge do comum.

 

Entendo que se o sistema não me mostra as informações completas devo te pontuar para uma análise de quem entende.

 

De qualquer forma agradeço.

 

Valeu.

 

 

 

Willian Nascimento

Adm / Fechamento

Tel: (11) 2344-7143 / (11) 2344-7144 Ramal: 3007 

Cel: (11) 94718-0165
JZ Remoções |  <http://www.jzresgate.com.br/> http://www.jzresgate.com.br 

Agilidade, Inovação e Eficiência em Transportes

 

 

 

De: Bruno Brito [mailto:notifications@github.com] 
Enviada em: sexta-feira, 28 de abril de 2017 17:20
Para: JZResgate/NASA-Issues <NASA-Issues@noreply.github.com>
Cc: JZWillian <willian.nascimento@jzresgate.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [JZResgate/NASA-Issues] Atendimentos pendente para analise , porem já analisados e faturados (#156)

 

Ok, será colocado na fila para desenvolvimento

**Comment by spmarco** [comment]
Conforme conversamos Willian vamos colocar como analisado o serviço quando todos os lançamentos foram gerados lote ou negociação. Caso crie um novo lançamento o serviço volta automaticamente para não analisado e somente quando gerar lote ou  negociação que ele volta para analisado.
Esta melhoria estará disponível na próxima versão.

**Comment by JZWillian** [comment]
Bom dia!

 

Ok!

Muito obrigado.

 

 

 

Willian Nascimento

Adm / Fechamento

Tel: (11) 2344-7143 / (11) 2344-7144 Ramal: 3007 

Cel: (11) 94718-0165
JZ Remoções |  <http://www.jzresgate.com.br/> http://www.jzresgate.com.br 

Agilidade, Inovação e Eficiência em Transportes

 

 

 

De: spmarco [mailto:notifications@github.com] 
Enviada em: segunda-feira, 3 de julho de 2017 18:43
Para: JZResgate/NASA-Issues <NASA-Issues@noreply.github.com>
Cc: JZWillian <willian.nascimento@jzresgate.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [JZResgate/NASA-Issues] Atendimentos pendente para analise , porem já analisados e faturados (#156)

 

Conforme conversamos Willian vamos colocar como analisado o serviço quando todos os lançamentos foram gerados lote ou negociação. Caso crie um novo lançamento o serviço volta automaticamente para não analisado e somente quando gerar lote ou negociação que ele volta para analisado.
Esta melhoria estará disponível na próxima versão.
