### ISSUE TITLE
[MELHORIA] Identificar notificados

### ISSUE THREAD

**Issue by brunohbrito** [JZResgate/NASA-Issues#157]
Sugestao proposta por Carlos Ama

- Aonde ocorreu o problema?
Tela de atendimento

- O que ocorreu?
Ao monitorarmos os serviços que são notificados, precisamos hoje, entrar na assistência para saber se o motorista aceitou ou não, ou se foi acionado direto, para assim cobrarmos uma posição do mesmo.

- Sugestao
Acredito que se no canto esquerdo onde clicamos para ver a viatura no mapa, nos casos em que notificamos e o motorista aceita o serviço, a cor muda-se para verde, nos auxiliaria e muito,pois evitaria o procedimento de abrir a assistência, e depois entrarmos no mapa para ver se o mesmo esta seguindo para o local.

 Com essa alteração já saberíamos que ele aceitou a notificação e somente iriamos no mapa para confirmar se ele esta seguindo ou não, agilizando nosso processo de monitoramento.

- Print da tela
![image](https://cloud.githubusercontent.com/assets/7241156/23278504/89b9f09e-f9f0-11e6-9f23-a09597f7d74a.png)

**Comment by MarceloMelloJZ** [comment]
Exato.

Marcelo Mello
Tel: (11) 2344-7138
Cel: (11) 94766-5105
JZ Remoções| http://www.jzresgate.com.br

**Comment by brunohbrito** [comment]
Estará disponivel na próxima versao.
![image](https://user-images.githubusercontent.com/7241156/27830906-da9fc74e-609e-11e7-8718-a9176f2581dc.png)
