### ISSUE TITLE
Nasa Fora de Ordem

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#158]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Relate Lista de atendimentos esta fora de ordem

- Numero do sinistro
*Ex: Diversos

- Horário da solicitação
*08:30hs

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

![image](https://cloud.githubusercontent.com/assets/23521482/23302194/76b9c880-fa6c-11e6-99d2-28ffa91f5e1a.png)

**Comment by brunohbrito** [comment]
Corrigido, por favor verifiquem.
