### ISSUE TITLE
31887669 Agendado não caiu para Pendente

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#159]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Relate com algum nivel de detalhes o que ocorreu, evite descrições genéricas do tipo: Não funciona

- Numero do sinistro
*Ex: 31173208

- Horário da solicitação
*Solicitação agendada para hoje as 10:00hs, porém não caiu para AGENDAMENTO

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

![image](https://cloud.githubusercontent.com/assets/23521482/23618206/5c406432-026e-11e7-9dc0-406568e1255a.png)

**Comment by brunohbrito** [comment]
Por favor, verifique se já está ok.

**Comment by reynaldogoncalves** [comment]
Bom dia! no momento em que aconteceu o problema automaticamente já voltamos o atendimento para pendente de acionamento. sendo assim fizemos o processo de forma manual.

**Comment by brunohbrito** [comment]
Isso significa que o problema foi resolvido?

**Comment by reynaldogoncalves** [comment]
Na minha opinião este atendimento sim, mas o foco do problema não visto que aconteceu novamente em outro caso ja encaminhado

**Comment by brunohbrito** [comment]
@reynaldogoncalves

Nao estou me referindo a este atendimento e sim ao fato de que os atendimentos agendados para hoje caíram na lista do Atendimentos em Curso. Portanto o problema foi resolvido e estou pedindo confirmação.

Poderia confirmar se os atendimento agendados estão aparecendo em curso?

**Comment by reynaldogoncalves** [comment]
Sim naquela data ok... os de hoje ok também.;
