### ISSUE TITLE
Captura Mapfre

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#16]
Prezados, bom dia!

As assistência da Mapfre não estão caindo na captura.

Por favor, podem verificar?

No aguardo,

**Comment by bhdebrito** [comment]
@Maramoret, obrigado por comunicar por aqui.

Ao que tudo indica houve alguma modificação interna na página da Mapfre. 

Sabe me dizer se visualmente houve alguma mudança?

Em todo caso, esse problema está pendente e iremos corrigi-lo precisaremos lançar uma nova versão da captura.

**Comment by Maramoret** [comment]
Não estamos sabendo de nenhuma alteração da Mapfre

**Comment by bhdebrito** [comment]
Houve modificações na pagina da mapfre.

Resolvido.
