### ISSUE TITLE
Serviços em duplicadade (579350) em duas CIAS

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#160]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Não estamos conseguindo exportar esse número do atendimento, pois o sistema está entendendo que ele já existe, pois no ano passado foi lançado um serviço de outra CIA com o mesmo número 

- Numero do sinistro
*Ex: 579350

- Horário da solicitação
*1615hs

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

![image](https://cloud.githubusercontent.com/assets/23521482/23766455/a024711c-04e3-11e7-8065-053965cbb0c1.png)

![image](https://cloud.githubusercontent.com/assets/23521482/23766493/cc870fbc-04e3-11e7-8210-53ec425f5b8a.png)

**Comment by brunohbrito** [comment]
Essa correçao estará disponivel na versao 2.5.3
