### ISSUE TITLE
31935502 - Erro do agendamento 

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#161]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Atendimento está agendado para as 10:30hs, porém não caiu para pendente acionamento

- Numero do sinistro
*Ex: 31935502 

- Horário da solicitação
*09:06hs

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

![image](https://cloud.githubusercontent.com/assets/23521482/23853500/b4b22ec2-07cb-11e7-91f0-16f55d4f6cc1.png)

**Comment by brunohbrito** [comment]
Resolvido
