### ISSUE TITLE
Baixa Automática EUROP

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#162]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela da CIA - FSM

- O que ocorreu?
As baixas automáticas não estão ocorrendo nessa página 

- Numero do sinistro
WO0000002968170

- Horário da solicitação
16:00

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by brunohbrito** [comment]
#181
