### ISSUE TITLE
Erro MAPA de trajeto 

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#163]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento, Historico
- O que ocorreu?
*Preciso ver o trajeto do motorista no item 1, porem al clicar pra ver ele só aparece as linhas azuis.

- Numero do sinistro
*Ex: 31781627

- Horário da solicitação
*15/03/2017 12h16

- Print da tela
*
![image](https://cloud.githubusercontent.com/assets/24894704/23955694/6d487942-0979-11e7-825b-ca869ca062bc.png)

**Comment by brunohbrito** [comment]
Os pontos desse atendimento não estão disponíveis no sistema. Um problema que aconteceu.

Só sera possivel obter a rota direto pelo site da positron.
