### ISSUE TITLE
Positron Travada

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#164]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Google Earth

- O que ocorreu?
As viaturas não estão espelhando corretamente o posicionamento

- Numero do sinistro
Não tem

- Horário da solicitação
1:58

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by brunohbrito** [comment]
Voltou a normalidade.
