### ISSUE TITLE
Falha do aplicativo na baixa de placa

### ISSUE THREAD

**Issue by gilsonlirio** [JZResgate/NASA-Issues#165]
Relato do colaborador Paulo Osiris em 16/03:

Ontem conversando com o Guimarães referente ao funcionamento do aplicativo ele me disse que ao tentar dar baixa na placa pelo aplicativo não funciona com todos os motoristas e oque achei mais interessante é que, por exemplo: Se ele esta parado em uma travessa da Coelho Lisboa com a Euclides pacheco por exemplo e o local para descarregar é Euclides Pacheco  e o GPS não reconhece. ele só consegue finalizar o serviço se movimentar o caminhão até a rua certa. Não sei se tem importancia essa informação, porem achei interessante passar adiante, pois foi uma observação do proprio motorista e se acaso o local aonde ele esta não for reconhecido pelo gps o mesmo não consegue fazer nada no aplicativo, como dar baixa na placa ou finalizar o serviço por exemplo. Isso foi palavras do proprio condutor

Aguardo retorno

**Comment by spmarco** [comment]
Sim, faz parte das regras ele conseguir baixar placa somente quando estiver no local correto, porque internamente quando o motorista baixa a placa o status muda para no local.
E sobre baixar a placa não funciona para todos os motoristas, ninguém falou nada e nem reclamou, para nós, estava funcionando.
Tem que entender o porque que alguns não estão funcionando e se é erro mesmo ou ele esta longe do local, o que faria ele cair nas regras de esta próximo do local correto.

Muitas vezes isso pode ser corrigido pelo atendente alterando o endereço para o local onde motorista esta, como sabemos nem sempre o ponto do google maps representa a realidade, principalmente em rodovias e em estradas mais longas e nestes casos é só o atendente mudar que tudo funciona.

**Comment by gilsonlirio** [comment]
Ok. Obrigado, Marco


  @ Alan, pode apurar isso, por favor?



*Gilson Lírio*
Gestão Comercial e Operações
Tel: (11) 2344-7148 / 98805-9675
*JZ Remoções *| http://www.jzresgate.com.br
*Agilidade, Inovação e Eficiência em Transportes*

*2017 - UM ANO NOTA 10!*

Em 16 de março de 2017 17:33, spmarco <notifications@github.com> escreveu:

**Comment by spmarco** [comment]
Aguardando a resposta

**Comment by spmarco** [comment]
Segundo resposta do Alan o app esta baixando a placa normalmente, provavelmente foi um problema pontual. Estou fechando, mas no primeiro problema que surgir não hesite em abrir um novo chamado
