### ISSUE TITLE
Duplicidade - 31976071

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#166]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
 Tela de atendimento, Historico, Detalhamento

- O que ocorreu?
Foi lança em duplicidade , uma delas foi cancelada em zero no sistema, porem quando vamos abrir o atendimento so abre a saida que esta cancelada .
- Numero do sinistro
31976071- Mondial 

- Horário da solicitação
21/03/2017 as 08h33

- Print da tela

![image](https://cloud.githubusercontent.com/assets/24894704/24145699/2768df1a-0e11-11e7-848a-b2d5d578718b.png)

![image](https://cloud.githubusercontent.com/assets/24894704/24145713/33f57946-0e11-11e7-9a8a-fb00344113d8.png)

**Comment by brunohbrito** [comment]
Resolvido
