### ISSUE TITLE
Nasa Travado

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#167]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Nasa esta travado não conseguimos exportar serviços 

- Numero do sinistro
*Ex: 31992504

- Horário da solicitação
*14:53

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

![image](https://cloud.githubusercontent.com/assets/23521482/24162396/24fd8a2a-0e46-11e7-8c24-08e0db90b35d.png)

**Comment by brunohbrito** [comment]
#168
