### ISSUE TITLE
31855994-falha -pagina em branco 

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#168]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de atendimento, Historico, Detalhe 
- O que ocorreu?
Consigo pesquisar o atendimento, porem não consigo visualizar os detalhes do mesmo a pagina fica em branco, sem informações 

- Numero do sinistro
31855994

- Horário da solicitação
21/03/2017 14h54

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/24894704/24162435/4724091c-0e46-11e7-9b07-44a3313cdd55.png)

![image](https://cloud.githubusercontent.com/assets/24894704/24162452/55066796-0e46-11e7-9ad4-e78664593a8d.png)

**Comment by brunohbrito** [comment]
Seu browser está trabalhando com cache, pressione CTRL+F5 para forçar a limpeza do Cache.
