### ISSUE TITLE
BARRA DE PESQUISA

### ISSUE THREAD

**Issue by JZMARRUDA** [JZResgate/NASA-Issues#169]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: BARRA DE PESQUISA NO CANTO SUPERIOR DA BARRA DE ATENDIMENTO.

- O que ocorreu?
*A barra de pesquisa não busca os caracteres digitados para realizar pesquisas especificas.

- Numero do sinistro
*Ex: JZ2017317114240

- Horário da solicitação
*15:12

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/24321843/24163313/f33a5e84-0e48-11e7-9af4-a8e04be16741.png)

**Comment by brunohbrito** [comment]
corrigido
