### ISSUE TITLE
Captura Nasa

### ISSUE THREAD

**Issue by diegosantos14** [JZResgate/NASA-Issues#17]
Nasa não esta Capturando serviços aceitos da pagina  BB Mapfre ( http://assistencia.bbmapfre.com.br/)
( https://assistencia.bbmapfre.com.br/EletronicActuationUIMvc/Home/?mwm=Mzg4ZWViZDUtNTk5MC00YTQyLTk4NzQtZTIzOWQ2OTc5MzZh&thirdCode=Nzg3OQ## )

obs: Favor verificar, problema persiste.

**Comment by bhdebrito** [comment]
@diegosantos14 

Acompanhe pelo chamado anterior #16

**Comment by diegosantos14** [comment]
ok
