### ISSUE TITLE
BARRA DE PESQUISA

### ISSUE THREAD

**Issue by JuanJuvencio** [JZResgate/NASA-Issues#170]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex:BARRA DE PESQUISA

- O que ocorreu?
*FILTROS NÃO FUNCIONAM CORRETAMENTE

- Horário da solicitação
21/03/2017 16:14
- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

![image](https://cloud.githubusercontent.com/assets/24394823/24166285/85de1a16-0e51-11e7-8f77-8b403e9bc6b0.png)

**Comment by brunohbrito** [comment]
Já há um chamado em aberto #169
