### ISSUE TITLE
ERRO NO FILTRO POR DATA DO HISTORICO

### ISSUE THREAD

**Issue by JZMARRUDA** [JZResgate/NASA-Issues#171]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Historico

- O que ocorreu?
* Quando tentamos selecionar o filtro por data o mesmo não deixa selecionar a data e incluir a mesma na pesquisa para adicionar demais filtros

- Numero do sinistro
*Ex: ERRO NA PESQUISA POR DATA

- Horário da solicitação
*16:26

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/24321843/24166716/015c7c9a-0e53-11e7-9db6-23be2f1972fa.png)

**Comment by brunohbrito** [comment]
Já esta ok
