### ISSUE TITLE
HISTÓRICO DE PESQUISA

### ISSUE THREAD

**Issue by JZMARRUDA** [JZResgate/NASA-Issues#172]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Historico / Barras de pesquisa.

- O que ocorreu?
* Depois de muito custo conseguir adicionar a data de hoje 21/03/2017 no filtro selecionando um dia anterior e depois selecionando o dia a ser pesquisado, mas ao selecionar a pesquisa ele pegou todos os serviços já feito pelo cliente não aplicando a data selecionada.

- Numero do sinistro
*Ex: Não se aplica.

- Horário da solicitação
*16:44

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/24321843/24167517/c99a2bd8-0e55-11e7-98ee-146ec4039358.png)

**Comment by brunohbrito** [comment]
Resolvido
