### ISSUE TITLE
Baixa Automatica EA não Está funcionando

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#173]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
tela dao FSM

- O que ocorreu?
A baixa automática não esta funcionando

- Numero do sinistro
WO0000003001496

- Horário da solicitação
08:05

- Print da tela

**Comment by brunohbrito** [comment]
Evite chamados em duplicidade #179
