### ISSUE TITLE
Captura USS (Não esta funcionando)

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#174]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Serviço não caiu na Captura

- Numero do sinistro
*Ex: 50.102.25704672/1 e 50.102.25704661/1

- Horário da solicitação
*10:48hs 

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

![image](https://cloud.githubusercontent.com/assets/23521482/24201302/6b2dcaf2-0eee-11e7-9823-25f4a224cc94.png)

**Comment by brunohbrito** [comment]
Api da Uss nao está respondendo. Precisa aguardar.

**Comment by brunohbrito** [comment]
Houve modificacao na api. Funcional novamente
