### ISSUE TITLE
Captura de Nenhum Cia Funcionando

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#176]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Após atualização do sistema Captura das Cias não esta funcionando

- Numero do sinistro
*Ex: 32008428

- Horário da solicitação
*14:10hs

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by brunohbrito** [comment]
Nao houve atualização de sistema. O servidor foi reiniciado.

**Comment by Maramoret** [comment]
De qualquer forma o sistema não esta capturando automaticamente os serviços aceitos. Por favor, pode verificar

**Comment by Maramoret** [comment]
![image](https://cloud.githubusercontent.com/assets/23521482/24261809/f32ebeb4-0fd6-11e7-8435-4fdc506f5d52.png)

**Comment by brunohbrito** [comment]
Alterado. 
![image](https://cloud.githubusercontent.com/assets/7241156/24265258/a2b48652-0fe1-11e7-9d9b-f5f55a0ad394.png)

Limpe o cache do browser
