### ISSUE TITLE
Atendimentos não Caem na Captura

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#177]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASA tela de captura

- O que ocorreu?
Os atendimentos não estão caindo na tela de Captura

- Numero do sinistro
592723

- Horário da solicitação
06:40

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by brunohbrito** [comment]
Evite criar chamados duplicados. Já há inclusive uma soluçao para o problema

#176
