### ISSUE TITLE
Ordem do NASA

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#178]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASA - Todas as telas

- O que ocorreu?
A ordem de aparecimento das assistências está invertida

- Numero do sinistro
32023703

- Horário da solicitação
14:18

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23550790/24333491/2a424830-122f-11e7-9c4a-5431434cf359.png)

**Comment by brunohbrito** [comment]
Corrigido
