### ISSUE TITLE
Placas EA não estão validando

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#179]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASA Tela de Validação de placa

- O que ocorreu?
Quando estamos colocando a placa no NASA o sistema informa que a placa está incorreta mesmo obtendo-a pelo esquema do NASA.. na pagina da CIA ele valida normalmente mas no NASA continua dizendo que está errada e depois de algum tempo ela desaparece

- Numero do sinistro
WO0000003023399

- Horário da solicitação
09:15

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/23550790/24404452/ebe37a86-1397-11e7-97f5-dce5beb7a0d9.png)

**Comment by brunohbrito** [comment]
Esse problema e no Webservice da Europ que retorna a informação de placa invalida.
