### ISSUE TITLE
CAPTURA SERVIÇOS MAPFRE 

### ISSUE THREAD

**Issue by eliasreis** [JZResgate/NASA-Issues#180]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de Atendimento

- O que ocorreu?
 Os serviços não estão caindo no captura

- Numero do sinistro
  Todos 

- Horário da solicitação
 Por volta das 11h20 os serviços da MAPFRE, pararam de cair no captura, todos estão sendo exportado manualmente.

**Comment by brunohbrito** [comment]
Resolvido
