### ISSUE TITLE
ERRO NA CAPTURA DE SERVIÇOS DA USS

### ISSUE THREAD

**Issue by JZMARRUDA** [JZResgate/NASA-Issues#181]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Captura de Serviços da pagina da USS.

- O que ocorreu?
A captura está puxando algumas informações fora de ordem da pagina da USS.

- Numero do sinistro
*Ex: 50.102.25736834/1

- Horário da solicitação
*14:55

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/24321843/24419908/4481bf7a-13c7-11e7-99fe-14033379c62a.png)

**Comment by brunohbrito** [comment]
Corrigido
