### ISSUE TITLE
Atendimento em Curso fora de Ordem

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#182]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Atendimento na tela em curso estão fora de ordem

- Numero do sinistro
*Ex: 31173208

- Horário da solicitação
*

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

![image](https://cloud.githubusercontent.com/assets/23521482/24425737/99a3dc4a-13db-11e7-864d-38eca08450fb.png)

**Comment by brunohbrito** [comment]
Na próxima versao irá entrar a correcao.

**Comment by brunohbrito** [comment]
Corrigido
