### ISSUE TITLE
CAPTURA EUROP

### ISSUE THREAD

**Issue by eliasreis** [JZResgate/NASA-Issues#183]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de atendimento

- O que ocorreu?
 Serviços da EUROP não estão caindo no captura 

- Numero do sinistro
WO0000003027856

- Horário da solicitação
 Por volta das 10h55 os serviços da EUROP pararam de cair no captura

**Comment by brunohbrito** [comment]
As 11:24 voltou a normalidade
