### ISSUE TITLE
Relatorio atendimentos Analisados por usuario

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#184]
Boa tarde!

Precisamos de um relatório que sejá possível identificar os serviços fechados por usuário.

A principio o mesmo precisamos enxergar a evolução de cada usuário. quem fechou o que em x período.

duvidas estarei a disposição.

**Comment by brunohbrito** [comment]
@JZWillian o relatório que atualmente te passamos não é fidedigno, pode haver inconsistências, afinal a fonte de dados tem outro objetivo.

Isso significa que precisamos criar um log para as acoes do usuário e fazer um relatorio em cima disso.

**Comment by JZWillian** [comment]
Bruno, 
Já existe hoje uma previsão para essa melhoria?

**Comment by JZWillian** [comment]
Bruno,
Já existe hoje uma previsão para essa melhoria?

 

Willian Nascimento

Adm / Fechamento

Tel: (11) 2344-7143 / (11) 2344-7144 Ramal: 3007 

Cel: (11) 94718-0165
JZ Remoções |  <http://www.jzresgate.com.br/> http://www.jzresgate.com.br 

Agilidade, Inovação e Eficiência em Transportes

 

 

 

De: Bruno Brito [mailto:notifications@github.com] 
Enviada em: quarta-feira, 29 de março de 2017 17:25
Para: JZResgate/NASA-Issues <NASA-Issues@noreply.github.com>
Cc: JZWillian <willian.nascimento@jzresgate.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [JZResgate/NASA-Issues] Relatorio atendimentos Analisados por usuario (#184)

 

@JZWillian <https://github.com/JZWillian>  o relatório que atualmente te passamos não é fidedigno, pode haver inconsistências, afinal a fonte de dados tem outro objetivo.

Isso significa que precisamos criar um log para as acoes do usuário e fazer um relatorio em cima disso.

**Comment by brunohbrito** [comment]
#215
