### ISSUE TITLE
CAPTURA USS

### ISSUE THREAD

**Issue by eliasreis** [JZResgate/NASA-Issues#187]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de atendimento

- O que ocorreu?
 Serviço da USS não esta caindo no captura

- Numero do sinistro
50 . 102 . 25750857 / 1

- Horário da solicitação
 Serviço aceito as 07h55 e o mesmo não caiu no captura, exportado manualmente

- Print da tela

![image](https://cloud.githubusercontent.com/assets/23520575/24547798/0b730428-15e8-11e7-9968-7ca34f7fc50e.png)

**Comment by Maramoret** [comment]
Prezados, bom dia!

Temos algum prazo para retorno da Captura dos atendimentos da USS?

No aguardo

**Comment by brunohbrito** [comment]
Nao, precisamos de um usuario e senha novo. Aguardando liberacao da USS.
