### ISSUE TITLE
WO0000003029733 - Chat Travado 

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#188]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Atendimento finalizado, porém chat aberto pelo motorista não sai do NASA

- Numero do sinistro
*Ex: WO0000003029733

- Horário da solicitação
*

- Print da tela

*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/23521482/24663884/84c9391a-192f-11e7-9316-99ad5eb606d3.png)

**Comment by brunohbrito** [comment]
Nao, precisamos de um usuario e senha novo. Aguardando a liberacao da USS

**Comment by spmarco** [comment]
corrigido
