### ISSUE TITLE
Frota SOMPO travada em Pontinho

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#189]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASA e Google Earth

- O que ocorreu?
A frota SOMPO está travada em potinho como se estivesse em atendimento

- Numero do sinistro
não tem

- Horário da solicitação
15:40

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by spmarco** [comment]
Corrigido
