### ISSUE TITLE
Erro Sistema

### ISSUE THREAD

**Issue by eliasreis** [JZResgate/NASA-Issues#19]
- Aonde ocorreu o problema?
 **Tela de Atendimento**

- O que ocorreu?
 **Ao Capturar e Salvar um novo atendimento, ocorre o erro informando que atendimento já existe

![Uploading Erro Sistema.JPG…]()

Numero do sinistro
 **Em todos os atendimento de  todas as Companhias**

**Comment by bhdebrito** [comment]
@eliasreis, obrigado,

Houve uma instabilidade de madrugada e os serviços foram restabelecidos.
