### ISSUE TITLE
Webservice Mondial - Frota.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#190]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Na liberação de viaturas conforme status e forçando a liberação.

- O que ocorreu?
Não esta liberando automaticamente na Mondial, temos que ocupar e liberar manualmente.

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/24709892/c34ec84a-19f1-11e7-81e0-dd35f812ef1c.png)

**Comment by brunohbrito** [comment]
O webservice da mondial provavelmente passou por algumas modificaçoe.

Do nosso lado funciona perfeitamente como esperado:
![mondial](https://cloud.githubusercontent.com/assets/7241156/24865947/351616d6-1ddf-11e7-96fa-113654265fbd.gif)

No entanto para alguns caso o Webservice mostra a seguinte mensagem de erro:
**O status atual do veiculo não permite troca manual de status.**

![image](https://cloud.githubusercontent.com/assets/7241156/24866019/676f7a8c-1ddf-11e7-968c-f02f55ba5ddd.png)
