### ISSUE TITLE
Captura da Mondial (Fora do Ar)

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#191]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Serviços não estão caindo na captura 

- Numero do sinistro
*Ex: 32094276 e 32094205

- Horário da solicitação
*10:43

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by brunohbrito** [comment]
Está normalizado.

Ocorreu problema devido as trocas de senha
