### ISSUE TITLE
O sistema não aceita inserir o cadastro de Grupo Fantasia e Tipo de Guincho

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#192]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Frota/Editar?idGuincho=38c24edc-a361-487e-b82d-7cec8662dda7

- O que ocorreu?
O sistema deixa preencher os campos Grupo Fantasia e Tipo de Guincho porem ao atualizar ele some.

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/24767870/f8d18e72-1ad6-11e7-98e3-9061e4b4d102.png)

**Comment by brunohbrito** [comment]
Sera corrigido na proxima versao
