### ISSUE TITLE
WO00000030522565 -Erro (Após edição)

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#193]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento, Histórico,Detalhes

- O que ocorreu?
*Temos 3 sinistros para esta placa , um deles a placa estava em sistema com apenas -???, editamos o atendimento para a correção da placa, porem apos a edição tentamos pesquisar em Histórico e o atendimento não aparece mais no NASA

- Numero do sinistro
*Ex: WO00000030522565

- Horário da solicitação
* 07/04/2017 10h30

- Print da tela

![image](https://cloud.githubusercontent.com/assets/24894704/24802267/b1749202-1b7d-11e7-8616-2f0f0f3d924c.png)

**Comment by brunohbrito** [comment]
Acompanhe pelo chamado #216
