### ISSUE TITLE
PROBLEMA DE CAPTURA EM AGENDADOS MAPFRE

### ISSUE THREAD

**Issue by JuanJuvencio** [JZResgate/NASA-Issues#194]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Na captura de Atendimento da Mapfre Agendados.

- O que ocorreu?
Não estão sendo capturados agendamentos da CIA MAPFRE,obrigando a ser feito o atendimento por meios manuais

- Numero do sinistro
*Ex: 8806340284

- Horário da solicitação
08/04/2017 15:09:20
- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/24394823/24831368/9b86b9f6-1c6e-11e7-9d7c-08a2fc8f6739.png)
![image](https://cloud.githubusercontent.com/assets/24394823/24831370/a8cede90-1c6e-11e7-915d-b24dbbf5dbab.png)

**Comment by spmarco** [comment]
Foi corrigido e já esta funcionando
