### ISSUE TITLE
ERRO AO UTILIZAR A FERRAMENTA DE APOIO

### ISSUE THREAD

**Issue by JZMARRUDA** [JZResgate/NASA-Issues#195]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: FERRAMENTA "APOIO"
- O que ocorreu?
* QUANDO FOI LANÇADO O APOIO NA ASSISTÊNCIA A MESMA FICOU CONGELADA E NÃO APARECE A OPÇÃO DE CONCLUIR OU FINALIZAR O SERVIÇO.

- Numero do sinistro
*Ex: 32109957

- Horário da solicitação
* 18:10

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/24321843/24832493/14e33acc-1c88-11e7-8f6e-592b9df803e1.png)
![image](https://cloud.githubusercontent.com/assets/24321843/24832497/261d9cb0-1c88-11e7-817e-0b5ad8280400.png)

**Comment by brunohbrito** [comment]
Corrigido.

![image](https://user-images.githubusercontent.com/7241156/28525070-5763a538-7059-11e7-841e-e9a6c9fd26e0.png)
