### ISSUE TITLE
Erro pagina Gerenciar comissão

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#196]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Agregado/GerenciarComissoes

- O que ocorreu?
Colocamos o filtro porem não para de carregar e mostra no inicio erro! Houve erro ao pesquisar os atendimentos 

- Horário da solicitação
16:43

- Print da tela

![image](https://cloud.githubusercontent.com/assets/24438478/24880242/14885056-1e10-11e7-852c-48f4f67eb0cf.png)
![image](https://cloud.githubusercontent.com/assets/24438478/24880248/1e8dd7ec-1e10-11e7-9e9b-7915e27b86aa.png)

**Comment by brunohbrito** [comment]
Correção sera liberada na próxima versao.
