### ISSUE TITLE
APP não abre 

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#197]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
APP JZ

- O que ocorreu?
Motoristas não conseguem abrir o APP

- Numero do sinistro
Não tem

- Horário da solicitação
08:05

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by spmarco** [comment]
Qual o motorista?
Qual o modelo do celular?
Qual erro aparece?

Para responder estas perguntas o melhor seria o motorista fazer um video mostrando o erro ou trazer aqui para vermos pessoalmente.

**Comment by reynaldogoncalves** [comment]
Boa tarde, foi somente nesse dia... ja esta resolvido, obrigado.
