### ISSUE TITLE
Dados dos Motorista Tela Frota

### ISSUE THREAD

**Issue by RvPaiva** [JZResgate/NASA-Issues#198]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de frota

- O que ocorreu?
*Colocar os dados dos motorista quando selecionar frota:
Exemplo
![capturar333](https://cloud.githubusercontent.com/assets/23521373/25353885/305aeecc-2907-11e7-8675-ff8bcc811918.PNG)
: 
Nome Completo.
RG.
CPF.
Modelo do Caminhão.
Marca do Caminhão.

- Horário da solicitação
*15h 58min

- Print da tela
*

!

**Comment by RvPaiva** [comment]
Em tempo...

Se possível colocar telefone de contato e Zello.

**Comment by brunohbrito** [comment]
Será incluido na próxima versão.

O telefone do Zello nao foi cadastrado no Nasa, por isso nao temos como exibir essa informaçao.

Teria que criar um chamado para poder salvar essa informaçao.

**Comment by RvPaiva** [comment]
Blz.. Valeu!!
