### ISSUE TITLE
Erro Efeturar Pesquisa

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#199]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de Histórico 

Ao efetuar pesquisa as informações na tela, apos atualização as informações não se repetem.

a cada atualização gera nova quantidade de atendimentos.

ateniosamente,

**Comment by brunohbrito** [comment]
Corrigido, disponivel na proxima versao
