### ISSUE TITLE
Erro ao alterar a especialidade 607017

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#201]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Serviço , Detalhe , Editar serviço 
- O que ocorreu?
Trata-se de um UTILITÁRIO , porem foi lançado como PESADO, ao clicar em editar para alterar apenas a especialidade o sistema solicitada dos os dados do atendimento (Todas as informações ja preenchidas ficam em branco )

- Numero do sinistro
607017 -Fácil 

- Horário da solicitação
25/04/2017 13:56

- Print da tela
![image](https://cloud.githubusercontent.com/assets/24894704/25397497/d45f657c-29be-11e7-91fc-da736d854b30.png)

![image](https://cloud.githubusercontent.com/assets/24894704/25397531/f09f74e8-29be-11e7-8b69-98cac2547eaa.png)

**Comment by brunohbrito** [comment]
Alterado para o novo componente do maps.

**Comment by Cristianerangel** [comment]
Boa Tarde!!
Oque quer dizer :  Alterado para o novo componente do maps ?  :)
Tentamos novamente , agora consta os dados normalmente , porem continua a  não altera a especialidade de PESADO para Utilitário

**Comment by JZMARRUDA** [comment]
Como conversado pelo Spark:
Nenhuma das alterações que estão sendo realizadas com a ferramenta edição estão sendo salvas.

**Comment by brunohbrito** [comment]
Tenta novamente
![erro](https://cloud.githubusercontent.com/assets/7241156/25434675/9e6c7d4c-2a63-11e7-973b-ab229f4de6af.gif)

**Comment by Cristianerangel** [comment]
Esta alterando , mas veja oque acontece ..
 32201272 - Fizemos o teste deste atendimento alterando de Leve para SubSolo (ok deu certo ), porem na tentativa de retornar a especialidade que estava ele não altera .. se clicar em editar ja consta como Leve , ao salvar e permanece como Sub Solo , fizemos o mesmo processo alterando novamente para Utilitário , porem para Leve não conseguimos alterar mais ...

**Comment by brunohbrito** [comment]
Isso parece Cache da sua maquina. 

Pressione CTRL+F5 para limpar o cache ou faça o procedimento:

![limpardadosnavegacao](https://cloud.githubusercontent.com/assets/7241156/25436419/9af5c366-2a69-11e7-9d37-1fefb69e3eac.gif)
