### ISSUE TITLE
Erro ao alterar especialidade 606740

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#202]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Serviço , Detalhe , Editar serviço

- O que ocorreu?
Trata-se de um UTILITÁRIO , porem foi lançado como PESADO, ao clicar em editar para alterar apenas a especialidade o sistema solicitada dos os dados do atendimento (Todas as informações ja preenchidas ficam em branco )

- Numero do sinistro
606740 -Fácil

- Horário da solicitação
25/04/2017  14:15

- Print da tela
![image](https://cloud.githubusercontent.com/assets/24894704/25398208/7d93c398-29c1-11e7-89fe-674d9c369d5b.png)

![image](https://cloud.githubusercontent.com/assets/24894704/25398227/9650b152-29c1-11e7-9b30-3ef6409964a5.png)

**Comment by brunohbrito** [comment]
#201
