### ISSUE TITLE
Erro ao alterar a especialidade 

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#203]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Serviço , Detalhe , Editar serviço

- O que ocorreu?
Trata-se de um UTILITÁRIO , porem foi lançado como PESADO, ao clicar em editar para alterar apenas a especialidade o sistema solicitada dos os dados do atendimento (Todas as informações ja preenchidas ficam em branco )

- Numero do sinistro
605641 -Fácil

- Horário da solicitação
25/04/2017  14:18

-Print 
![image](https://cloud.githubusercontent.com/assets/24894704/25398300/db4aeaac-29c1-11e7-8e64-e5391e1c8179.png)

![image](https://cloud.githubusercontent.com/assets/24894704/25398314/eae00204-29c1-11e7-9899-4712a46517ab.png)

**Comment by brunohbrito** [comment]
#201
