### ISSUE TITLE
ERRO NA FERRAMENTA DE EDIÇÃO

### ISSUE THREAD

**Issue by JZMARRUDA** [JZResgate/NASA-Issues#204]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: FERRAMENTE DE EDITAR

![image](https://cloud.githubusercontent.com/assets/24321843/25400149/0b7a5090-29c8-11e7-965a-7dca4e4ab369.png)

- O que ocorreu?
*Quando clicamos na ferramente Editar para alterar alguma informação no serviço já lançado ele abre como se fosse um novo serviço com todos os campos em branco

- Numero do sinistro
*Ex: 8806387690

- Horário da solicitação
*15:03
![image](https://cloud.githubusercontent.com/assets/24321843/25400252/59af8cf8-29c8-11e7-9a6e-d63e236b82c5.png)

- Print da tela
*
![image](https://cloud.githubusercontent.com/assets/24321843/25400289/6d4bffbc-29c8-11e7-9a95-baeaf08c9f64.png)

**Comment by brunohbrito** [comment]
Três chamados abertos com a mesma descriçao.

#202 #203 #201 

Acompanhe por algum deles.
