### ISSUE TITLE
PROBLEMAS NA CAPTURA DAS INFORMAÇÕES DE SERVIÇOS EUROP

### ISSUE THREAD

**Issue by JuanJuvencio** [JZResgate/NASA-Issues#205]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
ABERTURA DE ATENDIMENTO
- O que ocorreu?
NÃO É CAPTURADA NENHUMA INFORMAÇÃO QUANTO A VEÍCULO,LOCALIDADE,CLIENTE E PRODUTO 
- Numero do sinistro
WO0000003126868

- Horário da solicitação
25/04/2017 15:03
- Print da tela
![capturar endereco](https://cloud.githubusercontent.com/assets/24394823/25400699/bf5f52da-29c9-11e7-93cb-1e81bad98be5.PNG)
![capturar produto dados vhl](https://cloud.githubusercontent.com/assets/24394823/25400700/bf60adf6-29c9-11e7-93b7-29e939095cc9.PNG)

**Comment by spmarco** [comment]
Europ e Facil

**Comment by brunohbrito** [comment]
#208 
Fechado
