### ISSUE TITLE
Falha no Filtro -  EX  - 615439 

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#206]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
* Tela de atendimento, Historico, Relatorio Financeiro

- O que ocorreu?
Ao filtrar os atendimento no perido de 01/04/2017 a 20/04/2017 ( Itens apenas não analizados) 
Neste filtro não identificamos um atendimento do dia 18/04/2017

- Numero do sinistro
  615439 - Fácil  para este atendimento temos
1° saida em 18/04/2017 - Não analisada ( e não localizada no filtro) 
2° Saida em 19/04/2017 - Analisada e Já em lote

- Horário da solicitação
25/04/2017 15h57

- Print da tela
![image](https://cloud.githubusercontent.com/assets/24894704/25402752/1f61791e-29d0-11e7-806b-8f7cb9cf3e7e.png)

![image](https://cloud.githubusercontent.com/assets/24894704/25402771/3203b7da-29d0-11e7-8b40-67726b093561.png)

![image](https://cloud.githubusercontent.com/assets/24894704/25402799/429b4360-29d0-11e7-98ff-2cee5531b808.png)

**Comment by brunohbrito** [comment]
A opção de "Nao analisados" é somente para filtrar os itens da tabela, que já foram buscados.

![erro206](https://cloud.githubusercontent.com/assets/7241156/25436053/732bef32-2a68-11e7-9ab3-d8d56318d935.gif)

**Comment by Cristianerangel** [comment]
Bom Dia !
Bruno neste caso existem 2 item para o mesmo sinistro.
1 Analisado e outro não.

Neste caso se estamos filtrando (não analisados) ele não teria que aparecer em nossa pesquisa ?

**Comment by brunohbrito** [comment]
Cristiane o exemplo que criei acima está utilizando a data do dia 18/04, se você colocar o dia 19, ele irá aparecer.

Ps: Já está como analisado
