### ISSUE TITLE
CAPTURANDO SEM OS ENDEREÇOS/MODELO DO VEÍCULO 

### ISSUE THREAD

**Issue by Joelsonrodrigues** [JZResgate/NASA-Issues#208]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de atendimento

- O que ocorreu?
Após clicar para exporta o serviço, não foi exportada algumas informações referente ao atendimento como: endereços origem/destino, modelo do veículo, as opções estavam em branco.

- Numero do sinistro
622151

- Horário da solicitação
26/04/2017 ás 07:45

- Print da tela

![image](https://cloud.githubusercontent.com/assets/23551265/25431016/2d994d06-2a55-11e7-9b55-1c5eebf76a3c.png)

**Comment by brunohbrito** [comment]
Resolvido.
