### ISSUE TITLE
Geoposicionamento não esta visivel 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#209]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Frota/Geoposicao

- O que ocorreu?
Não estamos conseguindo visualizar as viaturas no mapa - geoposicionamento..
A tela fica toda cinza

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/25432873/92b9a062-2a5c-11e7-95d1-6fe89ce88535.png)

**Comment by brunohbrito** [comment]
Está usando o Chrome?

![image](https://cloud.githubusercontent.com/assets/7241156/25433216/fcd3fcf8-2a5d-11e7-9eeb-be4fcdc15195.png)

**Comment by MarceloMelloJZ** [comment]
Sim.

Marcelo Mello
Tel: (11) 2344-7138
Cel: (11) 94766-5105
JZ Remoções| http://www.jzresgate.com.br

**Comment by brunohbrito** [comment]
Marcelo, 

Traz seu pc para verificarmos, pois aqui na base todos acessam normalmente.
