### ISSUE TITLE
serviços sumindo do nasa

### ISSUE THREAD

**Issue by douglascostaabreu** [JZResgate/NASA-Issues#21]
NÃO ESTAMOS CONSEGUINDO MANDAR PRINT DA TELA!

SERVIÇOS ESTÃO SUMINDO DA TELA , FICANDO APENAS NO HISTORCO , NÃO ESTAMOS CONSEGUINDO COMENTAR N O SERVIÇO.

**Comment by viniciussantosrocha** [comment]
Serviço do GMOD 004 a saída de agora e o agendamento saída de base, 31196579, prestador ciente não estou conseguindo comentar no atendimento pelo histórico.

Serviço do GSALIC 16 a saída de agora que vai para base, 492728, consegui comentar mas não consegui lançar o equipamento patins que foi liberado.

Ambas as viaturas travadas em atendimento e os prestadores reclamando que não da pra ver o atendimento e anexar as fotos, Tudo passado verbal, via Zello e Tel.

**Comment by viniciussantosrocha** [comment]
![capturar](https://cloud.githubusercontent.com/assets/23520605/20462442/33d3b54c-af05-11e6-8981-fe47459b4af5.PNG)
![capturarsss](https://cloud.githubusercontent.com/assets/23520605/20462443/33d6838a-af05-11e6-8abb-f971df42f46f.PNG)

**Comment by viniciussantosrocha** [comment]
Segue as fotos de um dos atendimentos.

**Comment by viniciussantosrocha** [comment]
![capturar666](https://cloud.githubusercontent.com/assets/23520605/20462513/ed690074-af06-11e6-8f5a-ea5d270cd194.PNG)

**Comment by bhdebrito** [comment]
@viniciussantosrocha, não entendi seus problemas.

Aonde ocorreu o problema?
O que ocorreu?

Estou confuso com as informações passadas, me parecem ser problema distintos o que você relata em relação ao @douglascostaabreu.

@viniciussantosrocha se o problemas são diferentes, relate como um novo problema.

@douglascostaabreu Por favor, nas próximas vezes preencha o formulário inicial, o print de tela ajuda mas de longe não é o principal elemento.

O problema ainda permanece?
