### ISSUE TITLE
Erro APP - Destino

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#210]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
APP - tela de destino

- O que ocorreu?
Quando o motorista recebe o atendimento inicialmente o destino aparece com o mesmo bairro da origem, somente depois de algum tempo é que vem o destino correto, 

- Numero do sinistro
32217338

- Horário da solicitação
08:52

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by spmarco** [comment]
Fiz os testes e não aconteceu o mesmo erro, pode abrir um novo chamado novamente se isto se proliferar para muitos motorista
