### ISSUE TITLE
Integração Financeira (Robô de Lançamento de Ot's)

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#211]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Temos que desenvolver o robô de lançamento da Europ Extranet para Europ FSM.

**Comment by brunohbrito** [comment]
Como que anda esse processo?

A Europ já resolveu o problema de lentidao, já temos uma versao estável?

**Comment by JZWillian** [comment]
Bom dia!

 

Ainda não....

 

Estamos trabalhando com o extranet.

 

Aproveitado, pode colocar o robô para rodar?

 

O mesmo não rodou essa noite e enviaremos nota hoje.

 

Valeu.

 

 

 

Willian Nascimento

Adm / Fechamento

Tel: (11) 2344-7143 / (11) 2344-7144 Ramal: 3007 

Cel: (11) 94718-0165
JZ Remoções |  <http://www.jzresgate.com.br/> http://www.jzresgate.com.br 

Agilidade, Inovação e Eficiência em Transportes

 

 

 

De: Bruno Brito [mailto:notifications@github.com] 
Enviada em: quarta-feira, 3 de maio de 2017 09:36
Para: JZResgate/NASA-Issues <NASA-Issues@noreply.github.com>
Cc: JZWillian <willian.nascimento@jzresgate.com.br>; Author <author@noreply.github.com>
Assunto: Re: [JZResgate/NASA-Issues] Integração Financeira (Robô de Lançamento de Ot's) (#211)

 

Como que anda esse processo?

A Europ já resolveu o problema de lentidao, já temos uma versao estável?

**Comment by brunohbrito** [comment]
Eu havia desligado o robo.

**Comment by brunohbrito** [comment]
Previsao de quando a nova página do FSM estará funcionando plenamente?

**Comment by JZWillian** [comment]
Ainda não. 
Abs


Enviado do meu smartphone Samsung Galaxy.
-------- Mensagem original --------De: Bruno Brito <notifications@github.com> Data: 10/05/17  10:01  (GMT-03:00) Para: JZResgate/NASA-Issues <NASA-Issues@noreply.github.com> Cc: JZWillian <willian.nascimento@jzresgate.com.br>, Author <author@noreply.github.com> Assunto: Re: [JZResgate/NASA-Issues] Integração Financeira (Robô de Lançamento de Ot's) (#211) 
Previsao de quando a nova página do FSM estará funcionando plenamente?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JZResgate/NASA-Issues","title":"JZResgate/NASA-Issues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JZResgate/NASA-Issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@brunohbrito in #211: Previsao de quando a nova página do FSM estará funcionando plenamente?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/JZResgate/NASA-Issues/issues/211#issuecomment-300474690"}}}

**Comment by brunohbrito** [comment]
Devido a Europ ainda nao ter disponibilizado o sistema novo, estamos fechando o chamado.
