### ISSUE TITLE
Edição placa / atendimento não localizado.

### ISSUE THREAD

**Issue by carolineroiz** [JZResgate/NASA-Issues#216]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
 Tela de atendimento, Historico.

- O que ocorreu?
Editamos a placa do atendimento, porém ao pesquisar pela placa não localizamos o serviço editado.

- Numero do sinistro
WO0000003127746

- Horário da solicitação
27/04-17 10:56

Obs * Ja foi relatado 07/04/17 , porém esta prejudicando o fechamento dos serviços.

- Print da tela
![image](https://cloud.githubusercontent.com/assets/28104039/25487586/08526dde-2b3b-11e7-9d23-34829ad06562.png)

![image](https://cloud.githubusercontent.com/assets/28104039/25487633/311c095a-2b3b-11e7-9379-2d544771667a.png)

**Comment by spmarco** [comment]
corrigido
