### ISSUE TITLE
ENDEREÇO NÃO LOCALIZADO PELO NOVO MAPA

### ISSUE THREAD

**Issue by Joelsonrodrigues** [JZResgate/NASA-Issues#217]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de atendimento

- O que ocorreu?
Endereço não é encontrado, mesmo se jogar no mapa, copiar e colar também não encontra, até mesmo que não tem mais a opção de validar.

- Numero do sinistro
624353

- Horário da solicitação
28/04/2017 ás 08:25 hrs

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23551265/25527524/79643002-2bef-11e7-8913-b7ccbc823103.png)

**Comment by spmarco** [comment]
Isso vai acontecer mesmo, porque nem sempre a grafia vai estar condizente com a pesquisa, uma solução para isso é ir para o site do google e pesquisar o mesmo endereço. O que ele retornar de resultado vc copia e cola na pesquisa. Exemplo abaixo.

![google](https://cloud.githubusercontent.com/assets/10270935/25528744/9dd73d02-2bf5-11e7-933f-70e5628f10bb.gif)
