### ISSUE TITLE
Erro ao exportar sem endereço de destino.

### ISSUE THREAD

**Issue by vfelixjz** [JZResgate/NASA-Issues#219]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de exportação 

- O que ocorreu?
Erro quando exportamos serviço apenas com endereço de Origem    (no caso de sub solo e carga de bateria).

- Numero do sinistro
32231842 mondi

- Horário da solicitação
28/04/2017 09:50

- Print da tela
![captura endereco](https://cloud.githubusercontent.com/assets/23520756/25529609/3bbf83f0-2bf9-11e7-8a8e-6ad169144ef6.PNG)

**Comment by brunohbrito** [comment]
Alterado
