### ISSUE TITLE
viaturas em ponto

### ISSUE THREAD

**Issue by douglascostaabreu** [JZResgate/NASA-Issues#22]
JZ 169 , JZ 099

**Comment by viniciussantosrocha** [comment]
JZ 169 ainda está travado em atendimento, de pontinho, o mesmo esta perguntando por que esta em atendimento, foi comunicado que já esta sendo analisado pela T.I.

**Comment by bhdebrito** [comment]
@douglascostaabreu, as medidas tomadas até agora foram paliativas para remover o pontinho.

Por favor, nas próximas vezes, preencha os dados do formulário para  nos ajudar a resolver de uma vez por todas esse problema.

Liberado o **Gjz 169**

Obrigado.
