### ISSUE TITLE
CRIANDO SAÍDA DE BASE

### ISSUE THREAD

**Issue by Joelsonrodrigues** [JZResgate/NASA-Issues#220]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Criando saída de base

- O que ocorreu?
Ao criar saída de base, não está constando modelo e cor do veículo.

- Numero do sinistro
624052

- Horário da solicitação
28/04/2017 ás 06:30

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/23551265/25530190/ca6643ee-2bfb-11e7-9a1c-97f65d31ef5a.png)

**Comment by spmarco** [comment]
corrigido
