### ISSUE TITLE
[MELHORIA]CAPTURA DO CAMPO COMPLEMENTO EM ASSISTENCIAS MONDIAL 

### ISSUE THREAD

**Issue by vfelixjz** [JZResgate/NASA-Issues#221]
SUGESTÃO : 
CAPTURA DO CAMPO COMPLEMENTO EM ASSISTENCIAS MONDIAL 

PORQUE:
Facilidade na hora de exportar alem de constar mais informações na assistencia 

- Numero do sinistro
32233115 MONDIAL

- Horário da solicitação
28/04/2017 12:06

- Print da tela
![melhoria captura](https://cloud.githubusercontent.com/assets/23520756/25536404/19efd7b2-2c11-11e7-8b34-422a8b06de96.PNG)
![melhoria captura](https://cloud.githubusercontent.com/assets/23520756/25536607/d3d0eb26-2c11-11e7-82bb-125cbe64539c.PNG)

**Comment by brunohbrito** [comment]
Alterado
