### ISSUE TITLE
Serviços não localizados em 

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#222]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Relatorio/Servico/PorAcionamento

- O que ocorreu?
não aparece os atendimentos prestados pelo colaborador Americo na utilização dos filtros

![image](https://cloud.githubusercontent.com/assets/24438478/25538532/7b074bf4-2c19-11e7-82c6-598392b33fe1.png)

**Comment by brunohbrito** [comment]
@JZWillian 

O motorista Americo está com dois cadastros efetuados no sistema:

|Nome     | Ativo  | Data Cadastro | Data Ultima Modificacao | Usuario
|----------| ----  |---------------------- | ------------- | -------------
|AMERICO| Nao |2016-04-07 14:17:24 | 2017-04-12 16:44:38 | willian.nascimento@jzresgate.com.br
|AMERICO| Sim |2017-04-07 18:06:52 | 2017-04-07 18:07:04 | alberto.castro@jzresgate.com.br

Com uma rápida analise percebe-se que os acionamentos que você busca está selecionando o cadastro mais atual do Americo e consequentemente nao localiza nenhum no mês 03.

Para visualizar dados de produtividade é um pré-requisito o motorista estar ativo.

**Comment by JZWillian** [comment]
Bruno, 

 

Percebe que meu usuário esta aparecendo na modificação?

 

Eu ativei e inativei na época para ver se isso influenciava e não aprecia também.

 

Tive e procurar de outra forma, ex. frota que ele trabalhou, mesmo assim passei números inferiores para a Simone.

Acredito que o problema não seja esse que nos aponta.

 

Valeu.

 

 

 

Willian Nascimento

Adm / Fechamento

Tel: (11) 2344-7143 / (11) 2344-7144 Ramal: 3007 

Cel: (11) 94718-0165
JZ Remoções |  <http://www.jzresgate.com.br/> http://www.jzresgate.com.br 

Agilidade, Inovação e Eficiência em Transportes

 

 

 

De: Bruno Brito [mailto:notifications@github.com] 
Enviada em: sexta-feira, 28 de abril de 2017 15:40
Para: JZResgate/NASA-Issues <NASA-Issues@noreply.github.com>
Cc: JZWillian <willian.nascimento@jzresgate.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [JZResgate/NASA-Issues] Serviços não localizados em (#222)

 

@JZWillian <https://github.com/JZWillian> 

O motorista Americo está com dois cadastros efetuados no sistema:


Nome

Ativo

Data Cadastro

Data Ultima Modificacao

Usuario


AMERICO

Nao

2016-04-07 14:17:24

2017-04-12 16:44:38

willian.nascimento@jzresgate.com.br <mailto:willian.nascimento@jzresgate.com.br> 


AMERICO

Sim

2017-04-07 18:06:52

2017-04-07 18:07:04

alberto.castro@jzresgate.com.br <mailto:alberto.castro@jzresgate.com.br> 

Com uma rápida analise percebe-se que os acionamentos que você busca está selecionando o cadastro mais atual do Americo e consequentemente nao localiza nenhum no mês 03.

Para visualizar dados de produtividade é um pré-requisito o motorista estar ativo.

**Comment by brunohbrito** [comment]
William, 

Estou fazendo uma afirmação, é este o problema. 

O motorista que aparece na seleção do relatório é o motorista criado no dia 07/04/2017. Por essa data de criação ja da para perceber que não tem como este motorista ter acionamento no dia 01/03.

**Comment by JZWillian** [comment]
Bruno, 

 

Ok, considerada sua afirmação.

 

Porém o problema se torna outro, porque o sistema não mostrou os atendimentos do Américo 37 casos a menos que o devido.

 

Puxando puxado pelo nome Americo não parece nada, quando puxado pela Frota que ele trabalhou apareceram 95, mas olhando um a um acaba sendo devido mais de 130.

 

Caso aconteça o mesmo no próximo pagamento te encaminho antes.

 

Valeu.

 

 

 

 

 

 

Willian Nascimento

Adm / Fechamento

Tel: (11) 2344-7143 / (11) 2344-7144 Ramal: 3007 

Cel: (11) 94718-0165
JZ Remoções |  <http://www.jzresgate.com.br/> http://www.jzresgate.com.br 

Agilidade, Inovação e Eficiência em Transportes

 

 

 

De: Bruno Brito [mailto:notifications@github.com] 
Enviada em: sexta-feira, 28 de abril de 2017 16:07
Para: JZResgate/NASA-Issues <NASA-Issues@noreply.github.com>
Cc: JZWillian <willian.nascimento@jzresgate.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [JZResgate/NASA-Issues] Serviços não localizados em (#222)

 

William,

Estou fazendo uma afirmação, é este o problema.

O motorista que aparece na seleção do relatório é o motorista criado no dia 07/04/2017. Por essa data de criação ja da para perceber que não tem como este motorista ter acionamento no dia 01/03.

**Comment by brunohbrito** [comment]
William,

136 Atendimentos para o Motorista Americo, no Agregado Jz
![image](https://cloud.githubusercontent.com/assets/7241156/25547419/6ba8ea18-2c3d-11e7-800d-4b312843e742.png)

http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Demonstrativo/DetalhePagamentos?carimbo=37992121-4d07-460f-affd-ecdb28bf0547

Ativando o motorista americo no sistema e fazendo a busca só por motoristas no periodo selecionado, 136 atendimentos, o mesmo conforme printo acima:

![222](https://cloud.githubusercontent.com/assets/7241156/25547687/fba6baf4-2c3e-11e7-93fc-8d63ba7620c5.gif)

![image](https://cloud.githubusercontent.com/assets/7241156/25547720/326012b6-2c3f-11e7-88dd-c77344baae52.png)

Nao me parece ter problemas no sistema.

**Comment by JZWillian** [comment]
Estranho mano.
Juro que não estava puxando.
Mas que bom que deu certo.
Valeu 


Enviado do meu smartphone Samsung Galaxy.
-------- Mensagem original --------De: Bruno Brito <notifications@github.com> Data: 28/04/17  18:19  (GMT-03:00) Para: JZResgate/NASA-Issues <NASA-Issues@noreply.github.com> Cc: JZWillian <willian.nascimento@jzresgate.com.br>, Mention <mention@noreply.github.com> Assunto: Re: [JZResgate/NASA-Issues] Serviços não localizados em (#222) 
William,
136 Atendimentos para o Motorista Americo, no Agregado Jz


http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Demonstrativo/DetalhePagamentos?carimbo=37992121-4d07-460f-affd-ecdb28bf0547
Ativando o motorista americo no sistema e fazendo a busca só por motoristas no periodo selecionado, 136 atendimentos, o mesmo conforme printo acima:


Nao me parece ter problemas no sistema.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JZResgate/NASA-Issues","title":"JZResgate/NASA-Issues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JZResgate/NASA-Issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@brunohbrito in #222: William,\r\n\r\n136 Atendimentos para o Motorista Americo, no Agregado Jz\r\n![image](https://cloud.githubusercontent.com/assets/7241156/25547419/6ba8ea18-2c3d-11e7-800d-4b312843e742.png)\r\n\r\nhttp://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Demonstrativo/DetalhePagamentos?carimbo=37992121-4d07-460f-affd-ecdb28bf0547\r\n\r\nAtivando o motorista americo no sistema e fazendo a busca só por motoristas no periodo selecionado, 136 atendimentos, o mesmo conforme printo acima:\r\n\r\n![222](https://cloud.githubusercontent.com/assets/7241156/25547687/fba6baf4-2c3e-11e7-93fc-8d63ba7620c5.gif)\r\n\r\n![image](https://cloud.githubusercontent.com/assets/7241156/25547720/326012b6-2c3f-11e7-88dd-c77344baae52.png)\r\n\r\nNao me parece ter problemas no sistema."}],"action":{"name":"View Issue","url":"https://github.com/JZResgate/NASA-Issues/issues/222#issuecomment-298109233"}}}
