### ISSUE TITLE
SERVIÇO FINALIZADO AO VERIFICAR TRAJETO

### ISSUE THREAD

**Issue by Joelsonrodrigues** [JZResgate/NASA-Issues#223]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Histórico de atendimento

- O que ocorreu?
Na opção de trajeto feito pelo prestador está travada, não está aparecendo o percurso feito que fica verde.

- Numero do sinistro
32241076

- Horário da solicitação
01/05/2017 ás 09:23

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23551265/25579642/fecca1c2-2e4f-11e7-8952-5224638f2cfa.png)

**Comment by brunohbrito** [comment]
Ao efetuar os testes, este problema nao ocorreu.

![image](https://cloud.githubusercontent.com/assets/7241156/25615609/8a2201a4-2f0e-11e7-90db-46f81dadb2c4.png)
