### ISSUE TITLE
Erro Duplicidade - 32275126- Mondial 

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#226]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de atendimento, Historico, Detalhe 

- O que ocorreu?
* Foi consta lançado o mesmo sinistro 1 -Cancelado com a placa incompleta e 2 ° Normal com placa completa , porem ao clicar no atendimento para analisar ele nos detalha apenas o atendimento cancelado em zero.

- Numero do sinistro
32275126- Mondial 

- Horário da solicitação
08/05/2017 as 14:28

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/24894704/25816339/30cb1a6e-33fa-11e7-8da3-b20c3cf4a43b.png)

![image](https://cloud.githubusercontent.com/assets/24894704/25816528/b981ef72-33fa-11e7-9d51-8810cdd124d9.png)

**Comment by brunohbrito** [comment]
Corrigido
