### ISSUE TITLE
MELHORIAS -  Nome do segurado para o fechamento.

### ISSUE THREAD

**Issue by carolineroiz** [JZResgate/NASA-Issues#228]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de fechamento * melhorias

- O que ocorreu?
*Melhorias , solicitamos o nome do segurado no campo de detalhes.

- Numero do sinistro
*Ex: Sem sinistro

**Comment by brunohbrito** [comment]
Disponivel em produçao
