### ISSUE TITLE
Desempenho de prestador 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#229]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Relatorio/Frota/Desempenho

- O que ocorreu?
A tela não esta abrindo, esta dando um erro.

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/25895086/d0e6580a-3554-11e7-816d-5772b0e008a3.png)

**Comment by brunohbrito** [comment]
Resolvido
