### ISSUE TITLE
EXPORTAR ATENDIMENTO JÁ EXISTE

### ISSUE THREAD

**Issue by Joelsonrodrigues** [JZResgate/NASA-Issues#23]
Ao salvar o atendimento o sistema acusa que já existe. O sistema até salva mas fica aparecendo essa mensagem que o atendimento já existe.

![Uploading image.png…]()

**Comment by bhdebrito** [comment]
@Joelsonrodrigues , obrigado por relatar,

Para analisar precisamos de algumas informações:
Numero do sinistro
Dados do atendimento, pode ser o print da tela com as informações.
