### ISSUE TITLE
Melhoria - Monitoria pelo sinal do APP JZ 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#230]
Esta no cronograma de vcs usarmos o sinal do celular ( APPJZ ) para monitoria ao inves do sinal da Positron ?
A ideia é usar o sinal do APP para os novos prestadores que não receberam o positron e usar quando cair o sinal da Posotron.

Caso sim, tem previsão ?
Quando ?

No aguardo

**Comment by brunohbrito** [comment]
Acabou de entrar no cronograma.

**Comment by brunohbrito** [comment]
Em produçao.
