### ISSUE TITLE
Caminhão é notificado e não vincula automatico.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#231]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Notificação 

- O que ocorreu?
Caminhão é notificado e não vincula a frota automaticamente.
Nesse caso os dados do atendimento não aparece para o motorista.

- Numero do sinistro
50.137.43304601/1

- Horário da solicitação
09:24 hs 

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/25898766/d0bc078a-3563-11e7-9daf-575ab9427e2e.png)

**Comment by brunohbrito** [comment]
Corrigido
