### ISSUE TITLE
Melhoria no histórico de notificações

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#233]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Historico dos atendimentos 

- O que ocorreu?
Visualizacão mais facil e rapida das noticacões.

![image](https://cloud.githubusercontent.com/assets/23721255/25923256/fc625426-35b2-11e7-921f-42d1a48c7a24.png)

- Print da tela - Nessa parte do sistema é melhor a visualização.
![image](https://cloud.githubusercontent.com/assets/23721255/25923248/f3ca27a8-35b2-11e7-830d-136a36e69072.png)

**Comment by brunohbrito** [comment]
Já está no ar:
![image](https://cloud.githubusercontent.com/assets/7241156/25951590/8d83178e-3634-11e7-8d3f-9b49fddd3b47.png)

**Comment by MarceloMelloJZ** [comment]
Não visualizo da forma que eu envie, onde esta ?

Marcelo Mello
Tel: (11) 2344-7138
Cel: (11) 94766-5105
JZ Remoções| http://www.jzresgate.com.br

**Comment by brunohbrito** [comment]
Está em produçao:
![233](https://cloud.githubusercontent.com/assets/7241156/25952269/9cd48130-3636-11e7-832a-6a19eb1bc9c6.gif)

**Comment by brunohbrito** [comment]
Pressiona CTRL+F5
