### ISSUE TITLE
Melhoria no relatorio, frota de desempenho do prestador.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#234]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu a melhoria?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Relatorio/Frota/Desempenho#

- O que ocorreu?
Falta o indicador de Notificações expiradas.

- Print da tela
Captura de Tela 2017-05-11 às 10.06.48

**Comment by brunohbrito** [comment]
O que seria uma notificação expirada?

**Comment by MarceloMelloJZ** [comment]
Toca no celular do motorista e ele não aceita e não rejeita.
Muitos estão deixando expirar e no relatório não consta como recusa.
Precisamos dos recusados que já temos e dos expirados.


Em qui, 11 de mai de 2017 às 10:47, Bruno Brito <notifications@github.com>
escreveu:

**Comment by brunohbrito** [comment]
Em produçao.
