### ISSUE TITLE
Exportação da USS com horario errado.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#235]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Exportar atendimentos 

- O que ocorreu?
Quando exportamos o atendimento o horario esta vindo errado.

- Numero do sinistro
50.137.44015701/1
Todos os atendimentos.

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by brunohbrito** [comment]
Duplicado.
#251
