### ISSUE TITLE
Problema na Notificação enviada, travou em enviando

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#237]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Notificação 

- O que ocorreu?
A notificação foi enviada e não tivemos a resposta até agora, travou no status enviando 

- Numero do sinistro
WO0000003186590

- Horário da solicitação
10:05 hs
- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/26005957/20edce92-3711-11e7-8851-0e20bf162fe7.png)

**Comment by brunohbrito** [comment]
Está ok
