### ISSUE TITLE
URGENTE - Melhoria na tela de agendados

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#238]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de agendamentos 

- O que ocorreu?
Essa tela precisa ser evoluida de forma que fique parecendo com a de atendimento em curso.
Precisamos criar uma forma mais facil para conseguirmos acionar os agendados no dia anterior ou com horas de antecedencia.
A visualizacão precisa ser igual dos acionados em curso.

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/26006099/9fdcc44c-3711-11e7-88bf-8daffdf288ff.png)

**Comment by vfelixjz** [comment]
Poderiamos ter tambem a opção de cancelar atendimento ainda nesta tela 
![agendados](https://cloud.githubusercontent.com/assets/23520756/26285107/6d1979aa-3e1f-11e7-81a7-c657c19269a0.PNG)

do que ter que agendar para serviços imediatos e ai então cancelar este atendimento...

**Comment by brunohbrito** [comment]
Na próxima versao haverá uma nova tela para Agendados.
