### ISSUE TITLE
Webservice Frota Mondial

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#239]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Status GPS Mondial / NASA 

- O que ocorreu?
A troca de status automatica, liberar e ocupar GPS na Mondial não esta funcionando.
NASA NASA, Ocupar e Liberar, nenhuma das funções estão funcionando.

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/26006590/5d37112c-3713-11e7-93ea-e4732c6d8651.png)

**Comment by brunohbrito** [comment]
A nossa integraçao está ok e estimulando o webservice da novamente.
