### ISSUE TITLE
ENDEREÇO NO APLICATIVO.

### ISSUE THREAD

**Issue by viniciussantosrocha** [JZResgate/NASA-Issues#24]
ESTAMOS TENDO VÁRIOS RELATOS DOS MOTORISTAS QUE NÃO ESTÃO CHEGANDO OS DADOS DE ORIGEM DO VEÍCULO, RUA, REFERENCIAS E DESTINO.

OS PRESTADORES ESTÃO RECLAMANDO TAMBÉM QUE ESTÃO ACEITANDO O SERVIÇO E NÃO ESTA APARECENDO COMO ACEITO, CONTINUA COMO LIVRE O APLICATIVO.

**Comment by bhdebrito** [comment]
@viniciussantosrocha, obrigado pelo feedback,

Você fez uma **solicitação** de Notificação ou Acionamento pelo Nasa?

![image](https://cloud.githubusercontent.com/assets/7241156/20464272/11258eae-af2c-11e6-8b15-407deff3a920.png)

Para podermos trabalhar com efetividade, por favor, pegue uns dois desses motoristas e nos passe algumas informações: 

* Versão do Android
* Guincho - Placa ou Apelido que o motorista está logado
* Modelo do celular
* Usuário do Motorista (E-mail)

Se tiver duvidas, acesse [Como relatar um problema no aplicativo Jz Resgate](https://github.com/JZResgate/NASA-Issues/wiki/Como-relatar-um-problema-no-aplicativo-Jz-Resgate)

**Comment by douglascostaabreu** [comment]
Bruno efetuamos testes no aplicativo do JZ 106 , quando notificamos o prestador , o serviço toca mas na sequencia fica liberado , quando fazemos acionamento normal não toca.

**Comment by bhdebrito** [comment]
Ao que tudo indica, este problema já foi relatado anteriormente pelo @carloshenriqueama no problema #15 

Ambos sem dados suficiente para testes efetivos.

**Comment by bhdebrito** [comment]
@douglascostaabreu por favor, tente pegar os dados do celular do motorista, **Modelo do Android** e a **versão do Android**

Qual é o e-mail que motorista está utilizando?

Assim podemos elaborar o mesmo cenário do motorista e fazer testes.
