### ISSUE TITLE
Luan Não esta Alterando o Status 

### ISSUE THREAD

**Issue by alanoliveira158420** [JZResgate/NASA-Issues#240]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de Atendimento 

- O que ocorreu?
O Luan não esta alterando o Status de acionado para indo para o local 

- Horário da solicitação
10:14:00

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/23521390/26034128/1509a942-388e-11e7-91c3-4f4afc32f14b.png)

**Comment by brunohbrito** [comment]
Resolvido

**Comment by brunohbrito** [comment]
#241
