### ISSUE TITLE
Agendados não estão virando pendente de acionamento 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#241]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Atendimentos agendados não viraram pendente de acionamento, não enviamos os reboques.
Mais uma reclamacão.....

- O que ocorreu?
O serviço não virou pendente de acionamento, não mandamos o reboque.
Reclamação muito grande para eu resolver, são 10:45 hs e o agendamento era para as 08:00 hs.

- Numero do sinistro
32328971

- Horário da solicitação
23:48 hd 

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/26034413/8fda31ec-3892-11e7-8ed2-211a91c0a5de.png)

**Comment by brunohbrito** [comment]
Resolvido.
