### ISSUE TITLE
Produto INDIANA- Mondial

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#242]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASA- Tela de exportação

- O que ocorreu?
Quando recebemos um atendimento do produto INDIANA (Mondial) o NASA exporta com o produto IBBI, mesmo este produto não estando vinculado para esse cliente

- Numero do sinistro
32334109

- Horário da solicitação
08:35

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by brunohbrito** [comment]
@reynaldogoncalves 

O produto pode ser alterado na hora da criação do atendimento, se ele foi criado como IBBI é porque não foi alterado pelo atendente.

O Nasa faz a sugestão, a unica maneira de para com isto é removendo, consequentemente *todos* os atendimentos terao que selecionar o Produto.

**Comment by brunohbrito** [comment]
Estamos verificando

**Comment by brunohbrito** [comment]
Será resolvido na próxima versao
