### ISSUE TITLE
[Melhoria] Mostrar senha lançadas nos atendimentos na analise externa (control+mouse)

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#243]
Certifique-se de responder a estas perguntas:

Atendimento/Historico/Atendimento

- O que ocorreu?
precisamos que o sistema mostre a senha que esta lançada no atendimento com facilidade parecida com a demonstração de histórico (control+mouse).

precisamos dessa facilidade para que o fechamento não tenha a necessidade de abrir serviço por serviço consulte na pagina da cia a senha, lance no atendimento para depois analisar.

**Comment by brunohbrito** [comment]
Qual sua sugestao?

**Comment by MarceloMelloJZ** [comment]
Verdade, um atalho desse ajudaria bastante.


Marcelo Mello
Tel: (11) 2344-7138
Cel: (11) 94766-5105
JZ Remoções| http://www.jzresgate.com.br

**Comment by JZWillian** [comment]
Botão direito do mosse?
Me ajuda a pensar em algo.....




Enviado do meu smartphone Samsung Galaxy.
-------- Mensagem original --------De: Bruno Brito <notifications@github.com> Data: 17/05/17  14:02  (GMT-03:00) Para: JZResgate/NASA-Issues <NASA-Issues@noreply.github.com> Cc: JZWillian <willian.nascimento@jzresgate.com.br>, Author <author@noreply.github.com> Assunto: Re: [JZResgate/NASA-Issues] MOSTRAR SENHA LANÇADAS NOS ATENDIMENTOS NA ANALISE EXTERNA (CONTROL+MOUSE) (#243) 
Qual sua sugestao?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JZResgate/NASA-Issues","title":"JZResgate/NASA-Issues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JZResgate/NASA-Issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@brunohbrito in #243: Qual sua sugestao?"}],"action":{"name":"View Issue","url":"https://github.com/JZResgate/NASA-Issues/issues/243#issuecomment-302155033"}}}

**Comment by brunohbrito** [comment]
Um pequeno botão que ao clicar exibe as senhas de maneira rápida e fácil sem a necessidade de abrir nova janela:

![243](https://cloud.githubusercontent.com/assets/7241156/26169412/e86744a2-3b13-11e7-89cd-11d2a8704a7f.gif)

**Comment by JZWillian** [comment]
Bom dia!

Isso mesmo.

Abraço.

2017-05-17 15:17 GMT-03:00 Bruno Brito <notifications@github.com>:

**Comment by brunohbrito** [comment]
Estará disponível na próxima versão.
![243](https://cloud.githubusercontent.com/assets/7241156/26466011/9c13cf7a-4163-11e7-9b65-ef7fab6c0abd.gif)
