### ISSUE TITLE
Lentidão 

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#244]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
* Tela de atendimento, Historico, Detalhes

- O que ocorreu?
*Esta com lentidão em todos os processos , ao abrir, ao alterar qualquer dado do atendimento , ao gerar lote , ele fica carregando ..carregando..
- Numero do sinistro
32324495

- Horário da solicitação
18/05/2017 as 09h36

- Print da tela
*
![image](https://cloud.githubusercontent.com/assets/24894704/26202293/3559fe96-3bad-11e7-99fe-24bf2d318440.png)

![image](https://cloud.githubusercontent.com/assets/24894704/26202307/45faa32c-3bad-11e7-84fd-c6e23abdbd71.png)

**Comment by brunohbrito** [comment]
Resolvido
