### ISSUE TITLE
Desativar viatura GJZ.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#245]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Desativar viaturas 

- O que ocorreu?
A sistema não esta desativando uma viatura.
É a viatura que esta com a nomenclatura GJZ.
Atenção, essa placa tem outro cadastro GJZ 137 que esta ativo.

- Print da tela
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Frota/Editar?idGuincho=241bbaef-502f-4bf5-ac6e-97539af463c2

**Comment by brunohbrito** [comment]
Resolvido.
