### ISSUE TITLE
Sistema não esta ocupando e liberando as viaturas na Mondial.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#246]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Status da viatura NASA Mondial 

- O que ocorreu?
As viaturas não estão sendo liberadas ou ocupadas de forma automatica na pagina da Mondial 

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/26249621/b513650c-3c7d-11e7-977e-c75f0d4cab6c.png)

![image](https://cloud.githubusercontent.com/assets/23721255/26249632/bfde8c8c-3c7d-11e7-88d1-b6d778462b81.png)

**Comment by brunohbrito** [comment]
Alterado para a integração rodar a cada 1 minuto para sincronizar todas as viaturas
