### ISSUE TITLE
Apos notificado o serviço fica notificado e não Expira 

### ISSUE THREAD

**Issue by alanoliveira158420** [JZResgate/NASA-Issues#247]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
tela de atendimento NASA 

- O que ocorreu?
quando notificamos a frota a frota não expira se o motorista nao aceitar e fica notificado segue abaixo o print que foi notificado as 14:54 e ficou notificando e não expirou 

- Numero do sinistro
8806452447

- Horário da solicitação
15:06

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/23521390/26260744/c3184efc-3ca4-11e7-8c1b-6bad304cbfcb.png)

**Comment by brunohbrito** [comment]
Resolvido
