### ISSUE TITLE
SISTEMA LANÇA ATENDIMENTO SEM TRAÇO NA PLACA

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#248]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Nos dados do veiculo precisamos que segá padrão a informação de placa, se possível tudo maiúsculo e com Hífen 

- O que ocorreu?
Nosso operacional ao lançar um atendimento deixa a placa de formas diferentes (COM OU SEM HÍFEN, LETRAS MAIÚSCULA OU MINUSCULA)

- Numero do sinistro
*Ex: JZ2017518175213

- Horário da solicitação
*Tente ser assertivo nessa informação, informando data e horário com minuto. Nosso sistema possui logs de todas as interações, nos informar o horário permite rastrearmos, tente incluir o horário do windows no print de tela.

- Print da tela 
SEGUE EXEMPLO DO SERVIÇO 01 E SERVIÇO 02 DO MESMO SINISTRO
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/24438478/26352622/e5e7feaa-3f92-11e7-8946-ffb48d7ccd0e.png)

![image](https://cloud.githubusercontent.com/assets/24438478/26352648/fe319412-3f92-11e7-84ff-48efa5de1cef.png)

**Comment by MarceloMelloJZ** [comment]
Realmente ainda não foi solucionado a situação das placas, o NASA ainda aceita de formas diferente.

Marcelo Mello
Tel: (11) 2344-7138
Cel: (11) 94766-5105
JZ Remoções| http://www.jzresgate.com.br

**Comment by brunohbrito** [comment]
Iremos analisar aonde o sistema está permitindo entrar as placas sem mascara.

**Comment by spmarco** [comment]
Corrigido, estará disponível na próxima versão do NASA
