### ISSUE TITLE
ERRO AO EXPORTAR 

### ISSUE THREAD

**Issue by Joelsonrodrigues** [JZResgate/NASA-Issues#25]
![Uploading image.png…]()

**Comment by bhdebrito** [comment]
@Joelsonrodrigues, obrigado por relatar.

É muito importante preencher o formulário pré-disponível, veja como fica um relato de problema clicando [aqui](https://github.com/JZResgate/NASA-Issues/issues/1)

Duvidas em relatar um problema? Acesse [aqui](https://github.com/JZResgate/NASA-Issues/wiki/Como-relatar-um-problema-no-Site)
