### ISSUE TITLE
Sistema não vincula viatura apos notificacão aceita.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#250]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Sistema não vinculou o atendimento a frota apos o aceite da notificação

- O que ocorreu?
Apos o aceite da notificação a viatura não ficou vinculada 

- Numero do sinistro
32393615

- Horário da solicitação
21:11:25

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/26381944/ce7969fe-3ffe-11e7-8f32-6821a94779a3.png)

**Comment by spmarco** [comment]
Corrigido
