### ISSUE TITLE
Atendimentos da USS exportados com horario errado

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#251]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
O sistema traz todos os atendimentos exportados da USS com o horario errado.
O sistema traz com 3 horas apos o aceite, nesse caso foi aceito as 20:57 e sistema traz 23:57

- O que ocorreu?
O sistema traz os atendimentos com o horario errado.

- Numero do sinistro
50.102.46608822/1

- Horário da solicitação
20:58 hs

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/26382074/d0c72a4c-3fff-11e7-8f73-a441729a69d6.png)

**Comment by brunohbrito** [comment]
Resolvido.
