### ISSUE TITLE
Melhoria relatorio financeiro. 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#252]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu a melhoria ?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Relatorio/Faturamento/TipoRemocao

- O que ocorre?
O relatorio traz o faturamento de cada cia, volume e custo médio por tipo de serviço.

- O que sugere?
Precisamos de mais detalhes do custo de cada cia.
Exemplo:
Mapfre Reboque leve 300 atendimentos - R$ 33.963,05 - Custo Médio R$ 113,21
Precisa saber o que compoe os R$ 33.963,05
Saida = R$ xxxxx
Hora Parada = R$ xxxxxx
Patins = R$ xxxxxx
KM = R$ xxxxxxx

Todas as linhas que compoe o valor total de R$ 33.963,05 detalhado.

![image](https://cloud.githubusercontent.com/assets/23721255/26449012/67eeffcc-4126-11e7-93ff-eb53058ce55c.png)

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/26449105/c3358068-4126-11e7-8ee7-df6de9b2649d.png)

**Comment by brunohbrito** [comment]
Fazendo o filtro apenas pelo cliente, te traz esse nivel de detalhamento:

![image](https://cloud.githubusercontent.com/assets/7241156/26454373/4dc32d8c-413d-11e7-93ec-0ed12a8dbd00.png)

**Comment by brunohbrito** [comment]
Esquece, nao traz as informacoes dos lancamentos.

**Comment by spmarco** [comment]
Melhoria feita e já disponível no NASA
