### ISSUE TITLE
MELHORIA TELA ATENDIMENTO (INCLUSÃO DE SENHAS)

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#256]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Precisamos elaborar um forma em que a operação consiga incluir as senhas liberadas nas páginas da CIA no Campo senha da tela de valores do serviços, hoje eles não possuem esse acesso para inclusão, somente os usuario com acesso financeiro que conseguem editar e incluir essas informações.

- Numero do sinistro
*Ex: SENHAS DE FATURAMENTO

- Horário da solicitação
*

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by brunohbrito** [comment]
Estará disponível na próxima versao.

**Comment by brunohbrito** [comment]
Devido a duvidas recentes:
![image](https://user-images.githubusercontent.com/7241156/27826932-5e749ea0-608b-11e7-9570-42a60664d683.png)
