### ISSUE TITLE
ERRO AO ACESSAR A OPÇÃO DE LOCALIZAÇÃO NO NASA

### ISSUE THREAD

**Issue by Joelsonrodrigues** [JZResgate/NASA-Issues#257]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Atendimentos em curso 

- O que ocorreu?
Ao clicar na opção de localização para ver o percurso do serviço, fica somente carregando e trava o sistema.

- Numero do sinistro
651678

- Horário da solicitação
26/05/2017 ás 06:50

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23551265/26520437/ef7a3a3c-42a8-11e7-82a8-211a50ebc190.png)

**Comment by brunohbrito** [comment]
Resolvido
