### ISSUE TITLE
Exportação de Serviços Mondial (Produto Caixa)

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#258]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Atendimento produto Caixa e Sistema exportou como Sulamérica.

- Numero do sinistro
*Ex: 32415215

- Horário da solicitação
*Tente ser assertivo nessa informação, informando data e horário com minuto. Nosso sistema possui logs de todas as interações, nos informar o horário permite rastrearmos, tente incluir o horário do windows no print de tela.

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

![image](https://cloud.githubusercontent.com/assets/23521482/26521317/2bb877d0-42bc-11e7-936a-0e0530ca45f2.png)

![image](https://cloud.githubusercontent.com/assets/23521482/26521326/61b96a6a-42bc-11e7-83c3-e36803e2c6d8.png)

**Comment by MarceloMelloJZ** [comment]
Pessoal
Muito cuidado, se mandarmos caminhões errado novamente vai ser problema.
Tem que ter muita atenção com esse problema do NASA até que a TI arrume
isso.


Em sáb, 27 de mai de 2017 às 09:11, Maramoret <notifications@github.com>
escreveu:

**Comment by Maramoret** [comment]
OK vou orientar o pessoal aqui

*Mara Silva*
Atendimento
Tel: (11) 2344-7138 Cel. (11) 9 6914-2553
*JZ Remoções *| http://www.jzresgate.com.br​
*​Agilidade, Inovação e Eficiência em Transportes*

Em 27 de maio de 2017 09:24, MarceloMelloJZ <notifications@github.com>
escreveu:

**Comment by brunohbrito** [comment]
@Maramoret quem exporta é o atendente, o Nasa nunca travou a seleçao de produtos.

Como já disse para o Reynaldo em #242 , se desativar, será necessário selecionar o produto em **TODOS ** os atendimentos.

Voces que escolhem, desativa ou deixa?

**Comment by brunohbrito** [comment]
@MarceloMelloJZ Nao é problema no Nasa, temos que tomar cuidado com isso, nao faz sentido em apenas um serviço exportar errado, enquanto em todos os demais exportarem corretamente.

Outro detalhe, nao sei o que há de errado na sua tela, mas o Produto desse serviço é Sulamerica, conforme informado pela Mondial.

![image](https://cloud.githubusercontent.com/assets/7241156/26552395/500d7b06-445d-11e7-91d1-7a8b2ff31f14.png)
