### ISSUE TITLE
Melhoria na produtividade de atendimentos via GPS 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#259]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu a melhoria ?
Liberação de GPS ( caminhões ) automaticamente no raio de X KM ( campo para colocarmos a KM ).
Mondial 
EA 
Facil Assist 

Criar um campo para preenchermos a KM que pretendemos para aquele dia e hora.
Apos o preenchimento de X KM o sistema automaticamente a cada 1 minuto libera as viaturas no raio que preenchemos.

Obs.
Não são todas as viaturas que estão com o sinal aberto.

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by brunohbrito** [comment]
#77
