### ISSUE TITLE
Erro Nasa Alteração de trajeto 

### ISSUE THREAD

**Issue by vfelixjz** [JZResgate/NASA-Issues#26]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
 Tela de atendimento em curso 

- O que ocorreu?
entrei na aba ALTERAR TRAJETO,e depois de salvar ...informações foram salvas totalmente diferentes do que eu havia coloca...duplicando informações 

- Numero do sinistro
  31200336

**Comment by bhdebrito** [comment]
Obrigado, iremos analisar.

Movido para "A Fazer", assim que terminar a analise, comunicaremos.

**Comment by bhdebrito** [comment]
Modificado para próxima versao.
