### ISSUE TITLE
Melhoria e agilidade nos acionamentos 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#261]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu a melhoria?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Atendimento/AtendimentosEmCurso/PendenteAcionamento

- O que ocorreu?
Precisamos agilizar os acionamentos que estão demorados.
O ideal seria usarmos a tela Pendente de Acionamento com as 5 sugestões.

Obs. Os icones das 5 sugestões precisam ser com as cores que estão as viaturas.
A notificação tem que ser feita com apenas um clique em cima do icone desejado.

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/26564369/5321a7d2-44b6-11e7-9e3e-4d639134c645.png)

**Comment by brunohbrito** [comment]
#75
