### ISSUE TITLE
Agilidade nas notificações 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#262]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Notificação 

- O que ocorreu?
Precisamos reduzir o tempo para 1 minuto.

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by brunohbrito** [comment]
Marcelo, 

Hoje o tempo é de 2 minutos, mais 1 minutos para problemas com conexão de internet.
Tem certeza dessa decisão? Nao tem mais volta?

Iremos abaixar para 1 minuto o tempo do motorista

**Comment by spmarco** [comment]
As notificações já estão em 1 minuto no celular do agregado
