### ISSUE TITLE
Erro NASA ao editar 

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#263]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Atendimento, Historico, Detalhe

- O que ocorreu?
Erro ao editar o Lançamento/ Valores 

- Numero do sinistro
32421305

- Horário da solicitação
30/05/2017 08h39

- Print da tela
![image](https://cloud.githubusercontent.com/assets/24894704/26581570/a18520b8-4513-11e7-970e-9401b5019c6b.png)

![image](https://cloud.githubusercontent.com/assets/24894704/26581585/b8ba5654-4513-11e7-9b8f-4948debeedfb.png)

**Comment by brunohbrito** [comment]
Resolvido
