### ISSUE TITLE
APLICATIVO (CHASSIS NO CAMPO PLACA)

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#264]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento, Historico, Relatorio Financeiro

- O que ocorreu?
*Conforme contato do Paiva da TI os motoristas relatam que no atendimentos em que incluímos o chassis no campo placa não aparece no aplicativo.

- Numero do sinistro
*Ex: 

- Horário da solicitação
*T

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by spmarco** [comment]
Corrigido e já disponivel para os usuários
