### ISSUE TITLE
Agendamento quando Reservado Some da Tela

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#265]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela do NASA - Agendados

- O que ocorreu?
O agendamento quando deixamos reservado a algum motorista ele some da tela

- Numero do sinistro
32434887

- Horário da solicitação
15:20

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by brunohbrito** [comment]
Resolvido
