### ISSUE TITLE
Cliente CARBON- Não esta gerando lote

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#266]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
 Tela de atendimento, Historico, Detalhes 

- O que ocorreu?
Atendimentos do cliente Carbom não estão gerando lote, ao clicar em gerar lote da erro na pagina.

- Numero do sinistro
 jz201753153055

- Horário da solicitação
01/06/2017 
10h12

- Print da tela
![image](https://cloud.githubusercontent.com/assets/24894704/26681266/e34336fc-46b2-11e7-9ec3-d3b4f1c309ba.png)

**Comment by Cristianerangel** [comment]
Bom Dia !!!
Prezados alguma posição  sobre este caso?

**Comment by brunohbrito** [comment]
resolvido
