### ISSUE TITLE
NASA - GERAR LOTE NÃO ESTA FUNCIONANDO

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#267]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: ATENDIMENTO>>HISTORICO>>>DETALHES

- O que ocorreu?
*AO CLICAR NO BOTÃI GERAR LOTE PAGINA FICA CARREGANDO ATE APARECER MENSAGEM DE ERRO

- Numero do sinistro
*Ex:TODOS 

- Horário da solicitação
13:38
- Print da tela
![image](https://cloud.githubusercontent.com/assets/24438478/26690442/bb6e4e42-46cf-11e7-9d5d-025651b6ebc5.png)

**Comment by brunohbrito** [comment]
Resolvido
