### ISSUE TITLE
Agendamento 

### ISSUE THREAD

**Issue by RvPaiva** [JZResgate/NASA-Issues#268]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de agendamento!

- O que ocorreu?
Serviço agendado para ás 09h mas não apareceu para pedente de acionamento.
- Numero do sinistro
JZ201765175222

- Horário da solicitação
09H

- Print da tela
![tsusho](https://cloud.githubusercontent.com/assets/23521373/26829621/9e297f34-4a9c-11e7-9861-55fcecf8659e.PNG)

**Comment by spmarco** [comment]
Corrigido
