### ISSUE TITLE
Sinistro 8806167075 não esta gerando negociação

### ISSUE THREAD

**Issue by Jzjuliana** [JZResgate/NASA-Issues#269]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Atendimento/Historico/Detalhes

- O que ocorreu?
Lancei um novo item e não consigo gerar negociação

- Numero do sinistro
8806167075

- Horário da solicitação
17:31

- Print da tela

![image](https://user-images.githubusercontent.com/29238599/26850515-2423aaa6-4ade-11e7-9c05-8d61fbd047ad.png)

**Comment by spmarco** [comment]
Deve ter sido um problema temporário, entrei no serviço agora e gerei lote do mesmo.
