### ISSUE TITLE
ao acionar

### ISSUE THREAD

**Issue by ricardomellojz** [JZResgate/NASA-Issues#27]
Não estamos conseguindo acionar.

![image](https://cloud.githubusercontent.com/assets/23509659/20479699/578d0620-afc6-11e6-9df9-44808491635b.png)

**Comment by bhdebrito** [comment]
@ricardomellojz, algum atendimento está causando problemas em todos os demais.

Será que é pedir muito colaborar preenchendo o formulário que propusemos?

Se tem duvidas, acesse [aqui](https://github.com/JZResgate/NASA-Issues/wiki/Como-relatar-um-problema-no-Site)

**Comment by ricardomellojz** [comment]
Ok irei posicionar os demais.



*Ricardo C. Mello*
Atendimento
Tel: (11) 2344-7138
*JZ Remoções *| http://www.jzresgate.com.br

Em 21 de novembro de 2016 11:58, Bruno Brito <notifications@github.com>
escreveu:
