### ISSUE TITLE
32476855- Erro ao Gerar Lote 

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#270]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Tela de atendimento, Historico, Detalhes

- O que ocorreu?
* Atendimento com Status negociação, ao clicar em gerar lote esta dando erro e não gera o lote

- Numero do sinistro
* 32476855

- Horário da solicitação
* 08/06/2017 11h27

- Print da tela
*
![image](https://user-images.githubusercontent.com/24894704/26933650-7f40f5fa-4c3d-11e7-84d3-dac1108d2fed.png)

**Comment by spmarco** [comment]
Você consegue gerar lote porque não existe configuração de comissão cliente/agreado/categoria.  
O erro é porque o sistema não esta mostrando essa mensagem para você.
Fazendo esta configuração o lote será gerado normalmente e na próxima versão a mensagem será mostrada corretamente

**Comment by Cristianerangel** [comment]
Bom Dia !!
Desculpe , não entendi a sua colocação .
Acabei de tentar novamente e não consegui gerar o lote.
Desta vez alterei a comissão do AGR manualmente e mesmo assim sem sucesso ao gerar lote.
 do AGR manualmente e mesmo assim sem sucesso ao gerar lote.

**Comment by spmarco** [comment]
Quando digo que não tem configuração quero dizer que não tem uma pré configuração de comissão para o Agregado esta pré configuração é utilizada para fazer o calculo de sugestão da comissão, e como você mesmo disse estava errada porque faltava esta informação, porem mesmo você corrigindo internamente precisamos desta informação para fazer o calculo.
Fiz o cadastramento desta informação no banco a alguns minutos atrás pode tentar novamente que você vai conseguir.

Obs: Errei ao falar que você deveria fazer esta configuração porque ainda não existe uma tela desta no sistema

**Comment by Cristianerangel** [comment]
hum ..Agora entendi ..
Agora consegui .. Obrigada
