### ISSUE TITLE
BAIXA AUTOMATICA NA PAGINA MAPFRE x NASA 

### ISSUE THREAD

**Issue by vfelixjz** [JZResgate/NASA-Issues#272]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de atendimento ,

- O que ocorreu?
Quando baixamos a placa no NASA ou o próprio prestador baixa pelo aplicativo ,não está ocorrendo a baixa automática na pagina da MAPFRE  ,sendo assim estamos números no TMC que poderiam ser reduzidos.

8806508774

**Comment by spmarco** [comment]
Este problema ainda continua?

**Comment by spmarco** [comment]
Este problema ainda continua?
