### ISSUE TITLE
658163 Não consigo gerar lote

### ISSUE THREAD

**Issue by Jzjuliana** [JZResgate/NASA-Issues#273]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Atendimento/Historico/Detalhes

- O que ocorreu?
Não consigo gerar lote

- Numero do sinistro
658163

- Horário da solicitação
10:39

- Print da tela

![image](https://user-images.githubusercontent.com/29238599/26977963-12237e52-4d00-11e7-8439-57b96bd04877.png)

**Comment by spmarco** [comment]
Você não consegue gerar lote porque não existe **configuração de comissão cliente/agreado/categoria.**
O erro foi corrigido no chamado #270 e será disponibilizado no site na próxima publicação

**Comment by Jzjuliana** [comment]
Bom dia,

Não entendi sua mensagem.
Avaliei o atendimento novamente e o valor da comissão estava incorreto.
Estava como $90,00, retifiquei o valor para $49,50 e fiz uma nova tentativa
de gerar lote, porém deu o mesmo erro.






Atenciosamente,


*Juliana Teixeira*
Fechamento
Tel: (11) 2344-7144
*JZ Remoções *| http://www.jzresgate.com.br


2017-06-12 11:01 GMT-03:00 spmarco <notifications@github.com>:

**Comment by spmarco** [comment]
Quando digo que não tem configuração quero dizer que não tem uma pré configuração de comissão para o Agregado esta pré configuração é utilizada para fazer o calculo de sugestão da comissão, e como você mesmo disse estava errada porque faltava esta informação, porem mesmo você corrigindo internamente precisamos desta informação para fazer o calculo.
**Fiz o cadastramento desta informação no banco a alguns minutos atrás pode tentar novamente que você vai conseguir.**

Obs: Errei ao falar que você deveria fazer esta configuração porque ainda não existe uma tela desta no sistema

**Comment by Jzjuliana** [comment]
Marco,

Consegui agora gerar o lote.

Obrigada pelo auxilio




Atenciosamente,


*Juliana Teixeira*
Fechamento
Tel: (11) 2344-7144
*JZ Remoções *| http://www.jzresgate.com.br


Em 12 de junho de 2017 11:40, spmarco <notifications@github.com> escreveu:
