### ISSUE TITLE
ERRO TELA DE AGENDADOS

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#274]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento, Historico, Relatorio Financeiro

- O que ocorreu?
*Não estamos conseguindo utilizar o filtro de pesquisa para filtras os atendimentos por CIA e também não esta sendo possível ordenar os atendimentos para visualizar os agendamentos conforme data.

- Numero do sinistro
*Ex: 31489754

- Horário da solicitação
*

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

Não foi possível incluir a imagem

**Comment by spmarco** [comment]
Continua com este erro?

**Comment by spmarco** [comment]
corrigido
