### ISSUE TITLE
APP não atualiza.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#275]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Aplicativo

- O que ocorreu?
Diversos motoristas continuam dizendo que na maioria das vezes é preciso forçar a atualizacão do APP para atualizar o status.
Apos o acionamento ( não notificacão ) não atualiza automatico, é preciso que o atendimento avise para o mesmo atualizar.

**Comment by spmarco** [comment]
foi disponibilizada hoje uma correção do app onde inclui tambem a atualização automática cada 5 minutos
