### ISSUE TITLE
GERENCIAR COMISSÃO NÃO SALVA ALTERAÇÕES

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#276]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
PRESTADOR >>>GERENCIAR COMISSÃO

- O que ocorreu?
AO EDITAR UMA COMISSÃO PAGA ERRONEAMENTE O SISTEMA FICA CARREGANDO COM A MENSAGEM SALVANDO POR TODO O TEMPO POREM NÃO ALTERA VALORES

- Numero do sinistro
653098 ACIONADO PRESTADOR COM PAGAMENTO PARA JZ 

- Horário da solicitação
15:22
- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://user-images.githubusercontent.com/24438478/27048739-55176482-4f83-11e7-8e6c-268c00b6abb1.png)

**Comment by spmarco** [comment]
O filtro  que você fez nesta tela pega o mês de Maio inteiro então quando você pere para recalcular comissão você não esta sendo calculada somente para o sinistro que você filtrou na tabela, mas para todos os registros que foi pesquisado. 
Foi feita a correção, mas a tela não esta preparada para altera a comissão de somente um sinistro, para isso deveria-se colocar um filtro por sinistro.
Se for esta a necessidade também é só abrir um novo chamado para colocar mais um item no filtro
