### ISSUE TITLE
Inativar viatura.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#277]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Frota/

- O que ocorreu?
A viatura GJZ. já esta como inativa, porem fica aparecendo como disponivel no sistema.

- Print da tela
![image](https://user-images.githubusercontent.com/23721255/27059691-318f6d86-4fae-11e7-8ec9-2b3442a7d1f3.png)

![image](https://user-images.githubusercontent.com/23721255/27059695-35962ece-4fae-11e7-9662-376c82b80db2.png)

**Comment by brunohbrito** [comment]
Marcelo,

Nessa tela em especifico ela irá aparecer até que se altere o dia.
