### ISSUE TITLE
Notitficação aceita e que não vincula frota 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#278]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Frota/DadosOperacionais

- O que ocorreu?
Apos o aceite da notificacão o atendimento não fica vinculado ao serviço.

- Numero do sinistro
32523477

- Horário da solicitação
07:47 hs 

- Print da tela
![image](https://user-images.githubusercontent.com/23721255/27079207-25ed8f76-500d-11e7-87dd-fd9ed444715c.png)

**Comment by spmarco** [comment]
Igual a solicitação #250, vou atender pela outra que é mais antiga
