### ISSUE TITLE
Permissões Mobile 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#279]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Permissões Mobila

- O que ocorreu?
Não estamos conseguindo excluir do cadastro motoristas que não trabalham mais na empresa.

- Print da tela
![image](https://user-images.githubusercontent.com/23721255/27079604-a8b4c004-500e-11e7-8d77-a97ead833197.png)

**Comment by spmarco** [comment]
passe um usário para testarmos

**Comment by spmarco** [comment]
Marcelo, passe um motorista para excluir para testarmos

**Comment by spmarco** [comment]
a tela foi melhorada e já esta disponivel
