### ISSUE TITLE
NASA NAO ACEITA VALIDACAO DE PLACA NEM MUDANCA DE STATUS

### ISSUE THREAD

**Issue by carloshenriqueama** [JZResgate/NASA-Issues#28]
Ocorreu um erro inesperado, tente novamente.Ocorreu um erro inesperado, tente novamente.Ocorreu um erro inesperado, tente novamente.Ocorreu um erro inesperado, tente novamente.Ocorreu um erro inesperado, tente novamente.Ocorreu um erro inesperado, tente novamente.Ocorreu um erro inesperado, tente novamente.Ocorreu um erro inesperado, tente novamente.Ocorreu um erro inesperado, tente novamente.Ocorreu um erro inesperado, tente novamente.Ocorreu um erro inesperado, tente novamente.Ocorreu um erro inesperado, tente novamente.Ocorreu um erro inesperado, tente novamente.Ocorreu um erro inesperado, tente novamente.Ocorreu um erro inesperado, tente novamente.

**Comment by bhdebrito** [comment]
@carloshenriqueama, Não conseguimos te ajudar apenas com essa descrição, mas obrigado por relatar.
