### ISSUE TITLE
Relatorio de desempenho 13/05

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#282]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Relatorio/Frota/Desempenho#

- O que ocorreu?
O NASA não esta trazendo os numeros referente ao dia de ontem 13/05
Essa parte de relatorios não roda todas as madrugadas funcionando em D-1?

![image](https://user-images.githubusercontent.com/23721255/27129652-81ebb72c-50d9-11e7-8e82-1364af81008a.png)

**Comment by spmarco** [comment]
Todos os dias anteriores a hoje já estão funcionando
