### ISSUE TITLE
Aplicativo travando ao aceitar 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#283]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Notificacão de serviços 

- O que ocorreu?
Motoristas relatam que ao ser notificado os cliques na tela travam e expiram, não consegue aceitar o atendimento.
Acabei de tirar essa duvida também com o China que informa para os motoristas sempre clicar, fechar o aplicativo e abrir de novo, ao abrir de novo o atendimento esta aceito, virou pratica fazer dessa forma, dizem que fica rodando, rodando, rodando, ai tem que fechar e abrir novamente.

Motorista Azevedo GEURO 073 informa o mesmo problema. WO0000003302752	
 
Obs. Estamos sabendo dessas informacões porque estou começando a pegar no pé dos expirados.

![image](https://user-images.githubusercontent.com/23721255/27130720-db2fbd02-50dd-11e7-8756-7493dc645edf.png)

- Numero do sinistro
32533058

- Horário da solicitação
 08:21

- Print da tela
Captura de Tela 2017-06-14 às 08.26.48

**Comment by spmarco** [comment]
Fizemos aqueles teste e infelizmente não conseguimos reproduzir este erro.
Vou fazer alguns testes aqui, mas também ficar no aguardo de alguma resposta do atendimento se eles conseguem identificar algum padrão no erro
