### ISSUE TITLE
MAPA do historico muito pequeno 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#284]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Mapa do historico do atendimento 

- O que ocorreu?
O MAPA não fica grande, fica em um formato muito pequeno para analise.

- Print da tela
![image](https://user-images.githubusercontent.com/23721255/27130589-5281d68e-50dd-11e7-8f30-f8d301e9f857.png)

**Comment by brunohbrito** [comment]
Estará disponível na próxima versão.
