### ISSUE TITLE
Gerado lote porém não localizado no faturamenteo

### ISSUE THREAD

**Issue by carolineroiz** [JZResgate/NASA-Issues#286]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*:  Pesquisa Lote
 
- O que ocorreu?
* Serviço gerado lote no Nasa, porém ao tentar localizar na pagina de lote não é encontrado.

- Numero do sinistro
*: 9350255

- Horário da solicitação
*21/06/2017 10:45

- Print da tela
*
![image](https://user-images.githubusercontent.com/28104039/27387478-3a230b20-566f-11e7-9667-2b17e48066b2.png)
![image](https://user-images.githubusercontent.com/28104039/27387511-4e9c12ae-566f-11e7-8d57-abd4e9839ba8.png)

**Comment by spmarco** [comment]
Como assim? o primeiro print que você mandou não é da tela de lote?

**Comment by carolineroiz** [comment]
só gerou lote de 1, porém os 2 valores estão em lotes.

**Comment by spmarco** [comment]
Ok corrigido, agora os dois lotes estão aparecendo
