### ISSUE TITLE
Liberação de frota automatica - webservice 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#287]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Frota/AlteracaoEmMassaDadosOperacionais

- O que ocorreu?
A função de liberação conforme imagem abaixo não funciona.

![image](https://user-images.githubusercontent.com/23721255/27431006-39498708-5721-11e7-85ea-7e5a75bf8f0c.png)

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by brunohbrito** [comment]
Por favor faça o teste novamente

**Comment by MarceloMelloJZ** [comment]
Continua sem funcionar.


Marcelo Mello
Tel: (11) 2344-7138
Cel: (11) 94766-5105
JZ Remoções| http://www.jzresgate.com.br

**Comment by brunohbrito** [comment]
Resolvido.
