### ISSUE TITLE
Erro de atendimento 31357258

### ISSUE THREAD

**Issue by Jzjuliana** [JZResgate/NASA-Issues#288]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Atendimento/Historico/Atendimento#

- O que ocorreu?
Não é possível abrir o atendimento do cliente Mondial.
Existem 3 atendimento com mesmo numero porém para 2 para o mesmo cliente Speed Truck e o ultimo lançado para um cliente Mondial. Ao clicar no atendimento da Mondial ele abre o serviço da Speed

Obs. Estarei lançando um novo atendimento com mesmo numero porém /1 para o cliente Mondial pois precisamos fazer alterações.

- Numero do sinistro
31357258

- Horário da solicitação
22/06/2017
16:45hs

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://user-images.githubusercontent.com/29238599/27452766-359fd834-576a-11e7-871d-f13e658984b1.png)

**Comment by spmarco** [comment]
Não esta correto criar um novo atendimento só mudando o final, porque isto pode gerar confusão no futuro
Excluir o serviço que você criou, agora você já consegue trabalhar em cima do serviço da Mondial, só fazer os lançamentos novamente.
![image](https://user-images.githubusercontent.com/10270935/27456904-0ab28d92-5779-11e7-9605-4f557299ba49.png)

**Comment by Jzjuliana** [comment]
Marco, bom dia!

Ok, obrigada


*Juliana Teixeira*
Fechamento
Tel: (11) 2344-7144
*JZ Remoções *| http://www.jzresgate.com.br


2017-06-22 18:33 GMT-03:00 spmarco <notifications@github.com>:
