### ISSUE TITLE
PROBLEMAS NA CAPTURA MONDIAL

### ISSUE THREAD

**Issue by JuanJuvencio** [JZResgate/NASA-Issues#289]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Atendimentos mondial não estão sendo capturados

- O que ocorreu?
Atendimentos estão sendo aceitos e não estão aparecendo na tela de captura

- Numero do sinistro
32594569

- Horário da solicitação
23/06/2017 16h20
- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

não está indexando arquivo verificar.

**Comment by brunohbrito** [comment]
Os atendimentos estao sendo capturados, houve alguma intermitencia nesse atendimento
