### ISSUE TITLE
Frota 021 travada 

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#29]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Google Earth

- O que ocorreu?
Frota GJZ 021 - está travada em Pontinho

- Numero do sinistro
não tem

- Horário da solicitação
16:05

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by bhdebrito** [comment]
@reynaldogoncalves Obrigado,

Com o horário iremos conseguir reproduzir a situação em outro momento para efetuar os testes.

**Comment by bhdebrito** [comment]
@reynaldogoncalves, olá

O problema dos pontinhos está relacionado ao fato do motorista esta com acionamento para outro serviço, que não está "Em andamento".

Veja este atendimento agendado:

![image](https://cloud.githubusercontent.com/assets/7241156/20604466/b05ff864-b24d-11e6-9401-6bf83f0aeee3.png)
![image](https://cloud.githubusercontent.com/assets/7241156/20604473/b760097e-b24d-11e6-9b7a-d858b521ca1b.png)

Ele está acionado para um atendimento Agendado, isso pode ser feito através do acesso Financeiro que algumas pessoas da Operação possui.

Alguns usuários estão se beneficiando do acesso do financeiro para poder efetuar modificações nos agendados e com isso gera o problema dos pontinhos. Este acesso deveria ser exclusivo para modificar o veiculo, apenas.

Essas solicitações em breve serão implementadas no Nasa, até lá, por favor, quando utilizarem o acesso que possuem do financeiro, façam as alterações pontuais, como a troca de veiculo ou tipo de serviço.
