### ISSUE TITLE
Historico MAPA não esta mostrando correto a primeira saida.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#291]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Atendimento/Historico/Detalhes?id=32640694&servico=1

- O que ocorreu?
A visualizacão do historico do MAPA não mostra o local da remocão correto, esta mostrando os icones da segunda saida e não da primeira.
Obs, Estou clicando na primeira saida.

- Numero do sinistro
32640694

- Horário da solicitação
23:46
- Print da tela
![image](https://user-images.githubusercontent.com/23721255/27762597-9e95a746-5e4b-11e7-95b4-6645fef50595.png)

![image](https://user-images.githubusercontent.com/23721255/27762598-a705ec7e-5e4b-11e7-93e8-b6b5c1f4d484.png)

**Comment by brunohbrito** [comment]
Estará disponivel na próxima versao.
