### ISSUE TITLE
Mapa do Historico e rota da viatura é muito pequeno e não aumenta de tamanho.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#292]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Historico dos serviços, mapa com rota e icones do trajeto.

- O que ocorreu?
O MAPA é muito pequeno e não aumenta de tamanho.

- Numero do sinistro
Todos.

- Horário da solicitação
Todos

- Print da tela
![image](https://user-images.githubusercontent.com/23721255/27762608-f34278fa-5e4b-11e7-8f48-e1577add022f.png)

**Comment by brunohbrito** [comment]
Duplicado.

#284
