### ISSUE TITLE
Historico de mudanças nas viatura.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#293]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Frota/DadosOperacionais

- O que ocorreu?
O sistema só traz as ultimas 5 mudanças na viatura.
O ideal é seria visualizar as ultimas 20.
 
- Print da tela
![image](https://user-images.githubusercontent.com/23721255/27806664-4620634e-6012-11e7-9c4b-f0cb02feacf5.png)

**Comment by brunohbrito** [comment]
Em producao.
