### ISSUE TITLE
Erro NASA - 32638494

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#295]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Tela de atendimento, Historico, 

- O que ocorreu?
*Não visualizamos o detalhamento da assistência a tela fica em branco, qualquer sinistro que clicar para abrir fica desta forma 

- Numero do sinistro
*32638494

- Horário da solicitação
* 04/07/2017 10h50

- Print da tela
*
![image](https://user-images.githubusercontent.com/24894704/27832891-d2168ad8-60a6-11e7-8783-6305ea4161fb.png)

**Comment by brunohbrito** [comment]
Resolvido:

![image](https://user-images.githubusercontent.com/7241156/27833407-1c6c753c-60a9-11e7-83fe-ffbfa3f4171d.png)
