### ISSUE TITLE
Histórico não abre

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#296]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASA - tela de histórico 

- O que ocorreu?
Quando clicamos nos ... para abrir histórico ele não abre,NASA fica em branco

- Numero do sinistro
32656321

- Horário da solicitação
11:06

- Print da tela

**Comment by brunohbrito** [comment]
Duplicado.
#295
