### ISSUE TITLE
Melhoria Nasa - Visualização de senhas

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#297]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
nasa / tela principal / 

- O que ocorreu?
Preciso se possivel na tela principal do nasa na parte de valores já contenha a informacao da senha // se está ou não lançada 

- Numero do sinistro
32662932

- Horário da solicitação

- Print da tela

**Comment by brunohbrito** [comment]
Estará disponível na próxima versao.
