### ISSUE TITLE
Alteracões em Massa

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#298]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/nasa/jz-resgate/Brasil/Frota/AlteracaoEmMassaDadosOperacionais

- O que ocorreu?
Melhoria -  Colocar os bairros e as cidades em ordem alfabetica, assim fica mais rapido e facil de utilizar.

- Print da tela

![image](https://user-images.githubusercontent.com/23721255/27840648-21e06104-60d1-11e7-8b4b-8c1c4c6049aa.png)

**Comment by brunohbrito** [comment]
Alterado
