### ISSUE TITLE
Visualização de serviço aceito por parte do motorista

### ISSUE THREAD

**Issue by carloshenriqueama** [JZResgate/NASA-Issues#299]
Quando notificamos o serviço e o motorista aceita, dentro da assistência consta o mesmo em verde.

Gostaria de saber se não há a possibilidade de que essa cor verde quando aceita pelo motorista, apareça no icone que utilizamos para consultar o mapa na tela do nasa .(balãozinho lado esquerdo).

Esta alteração de cor agilizaria na cobrança de motoristas que por algum motivo foi acionado diretamente, chamando a atenção para a cor.

**Comment by spmarco** [comment]
O sistema estava com uma falha que os motoristas estavam explorando onde após aceitar o serviço eles saiam e entravam de novo, tendo a falsa impressão de que é mais rápido, com isso o NASA estava recebendo duas solicitações de aceito e como não estava preparado para isso o motorista era acionado e desacionado na sequência. Fiz a correção e agora todo o motorista que aceita ele vai mudar de cor, que é o padrão desde sempre, e lançar um raio em direção ao destino.
