### ISSUE TITLE
Motorista Arnaldo Frota JZ 113 DTB-0148 

### ISSUE THREAD

**Issue by alanoliveira158420** [JZResgate/NASA-Issues#30]
Motorista tem um moto G1 e não esta conseguindo receber as notificações de todos os serviços

**Comment by spmarco** [comment]
Por favor entre em contato com o motorista e pergunte.
1. Desde quando esta assim?
2. Além de não receber o acionamento/notificação os status também não estão mudando?
3. As ações feitas por ele, troca de status do caminhão, no local, concluir ele esta conseguindo fazer?
4. Ele consegue perceber alguma coisa que sempre acontece?

**Comment by bhdebrito** [comment]
Ele recebeu o atendimento via Acionamento. No app consegue fazer outras ações:

Envio de imagem

![image](https://cloud.githubusercontent.com/assets/7241156/20532447/2cf60302-b0c1-11e6-87f5-51c9a638ce72.png)

Concluir atendimento:

![image](https://cloud.githubusercontent.com/assets/7241156/20532534/82887b24-b0c1-11e6-830e-8c01330a97e4.png)

**Comment by spmarco** [comment]
Corrigido
