### ISSUE TITLE
Horário Exportado Errado

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#301]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Nasa, tela de exportação

- O que ocorreu?
os horários ao exportar estão vindo atrasados 

- Numero do sinistro
WO0000003376065 / 690079 / 690288 / JZ201773171412

- Horário da solicitação
10:06

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by spmarco** [comment]
Isto continua acontecendo?

**Comment by reynaldogoncalves** [comment]
aconteceu sometne naquela ocasiao, grato.

**Comment by spmarco** [comment]
ok
