### ISSUE TITLE
TELA DE STATUS FINANCEIRO NÃO ESTA APARECENDO PLACA

### ISSUE THREAD

**Issue by JZFelipe** [JZResgate/NASA-Issues#302]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Fechamento >>>Histórico >>> Status Financeiro

- O que ocorreu?
Nesta tela não esta carregando a placa/chassi dos atendimentos.

- Numero do sinistro
JZ2017621114556

- Horário da solicitação
14:54

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://user-images.githubusercontent.com/29927570/27877719-228900fe-6192-11e7-8968-80a5ab53f19e.png)

**Comment by spmarco** [comment]
Este serviço realmente não tem placa. Aconteceu alguma coisa com o serviço onde a placa foi removida.
