### ISSUE TITLE
{MELHORIA} CAPTURA USS 

### ISSUE THREAD

**Issue by vfelixjz** [JZResgate/NASA-Issues#303]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Exportar serviços USS

- O que ocorreu?
Não capturamos informações descritas no campo "CONDIÇÕES" na assistência USS, e depois de aceito o serviço não temos mais acesso a tais informações que são de grande importância. 

- Numero do sinistro
12.4.47069391/1

- Horário da solicitação 
07/07/2017 09:20

![melhoria uss](https://user-images.githubusercontent.com/23520756/27962118-4732c860-6307-11e7-952e-b060a9267d1a.png)

**Comment by brunohbrito** [comment]
Em produçao.
