### ISSUE TITLE
ORDEM ALFABÉTICA DOS CLIENTES EM "CONCLUIDOS"

### ISSUE THREAD

**Issue by gilsonlirio** [JZResgate/NASA-Issues#306]
Bom dia.

Por favor, vejam a possibilidade de colocar os clientes em ordem alfabética para as pesquisas de serviços concluídos.

No aguardo

![image](https://user-images.githubusercontent.com/23508636/28017714-d11c43bc-6550-11e7-838a-6cab859e018e.png)

**Comment by brunohbrito** [comment]
Devido a baixa complexidade, iremos disponibilizar na próxima versao

**Comment by gilsonlirio** [comment]
Ok. Obrigado

**Comment by spmarco** [comment]
Corrigido estará disponível na próxima versão do NASA
