### ISSUE TITLE
Serviço Apos aceito Desvinculou da frota  

### ISSUE THREAD

**Issue by alanoliveira158420** [JZResgate/NASA-Issues#308]
Aonde ocorreu o problema?
Tela de atendimento

- O que ocorreu?
Serviço apos acionado desvinculou da frota  

- Numero do sinistro
WO0000003397235 

- Horário da solicitação
11:49

*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://user-images.githubusercontent.com/23521390/28074776-d25cc1cc-662f-11e7-8a51-e71970933e07.png)

![image](https://user-images.githubusercontent.com/23521390/28076124-0d7139ba-6634-11e7-8a15-2c5188dabdb3.png)

![image](https://user-images.githubusercontent.com/23521390/28076154-1f108f2c-6634-11e7-9163-2d752d255330.png)

**Comment by spmarco** [comment]
vamos aguardar se acontece de novo para identificarmos qual a causa do problema

**Comment by spmarco** [comment]
Corrigido
