### ISSUE TITLE
Assistência sendo exportada errada

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#309]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASa , tela de exportação

- O que ocorreu?
Todo serviço da Mondial cujo produto é Peugeot Citroen o NASA puxa como produto IG

- Numero do sinistro
32709386

- Horário da solicitação
15:00

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by spmarco** [comment]
![image](https://user-images.githubusercontent.com/10270935/28435583-fd3ff59e-6d69-11e7-91ed-5dd506fefe8d.png)

Não vai achar mesmo porque neste caso esta invertido, no NASA esta CITROEN PEGEOUT  e na importação esta PEGEOUT CITROEN.
O sistema tentou chegar o mais perto possivel mas neste caso não há o o que fazer. 
Uma das alternativas é corrigir no NASA o produto ou alguém com acesso em gerenciar cliente e incluir PEGEOUT CITROEN.
Porem no caso de corrigir no NASA existe a possibilidade da Mondial mudar novamente.

**Comment by spmarco** [comment]
corrigido
