### ISSUE TITLE
Erro ao Exportar Fácil

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#310]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Nasa tela de exportar

- O que ocorreu?
Quando tento exportar algum atendimento da Facil Assist o sistema apresenta erro e não permite 

- Numero do sinistro
696847

- Horário da solicitação
15:06

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by brunohbrito** [comment]
Resolvido.

Os atendimentos da facil estao exportando!
