### ISSUE TITLE
HISTORICO FORA

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#316]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Estamos tentando buscar assistencia no historico, porém fica somente processando

- Numero do sinistro
*Ex: 702878/703076

- Horário da solicitação
*09:29

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

![image](https://user-images.githubusercontent.com/23521482/28317016-92596d3e-6b9b-11e7-83a5-c23c4265c91b.png)

**Comment by spmarco** [comment]
corrigido
