### ISSUE TITLE
Notificação aceita não vinculou no atendimento 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#317]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Vincular viatura ao atendimento apos a notificação aceita.

- O que ocorreu?
Apos o aceite do motorista o mesmo informa que não esta aparecendo nada no APP, desligou, ligou, atualizou e depois descobrimos que o NASA não vinculou.

- Numero do sinistro
50.102.47180656/1

- Horário da solicitação
10:31

- Print da tela
![image](https://user-images.githubusercontent.com/23721255/28319929-9afa4b7a-6ba5-11e7-90e0-5801b4b913d0.png)

**Comment by spmarco** [comment]
vamos aguardar se acontece de novo para identificarmos qual a causa do problema

**Comment by spmarco** [comment]
igual ao #308 acompanhe por ele , este será fechado
