### ISSUE TITLE
Produto Caixa exporta Como Sulamerica

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#318]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASA tela de exportar

- O que ocorreu?
Quando recebemos um atendimento do produto Caixa o NASA exporta  como Sulamerica mesmo tendo esse produto registrado no cliente 

- Numero do sinistro
32771583

- Horário da solicitação
10:19

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by spmarco** [comment]
![image](https://user-images.githubusercontent.com/10270935/28465571-9ff4a006-6dff-11e7-8bfd-fdaf2ad55fea.png)

Fiz o teste com o sinistro **32771583** e o que esta em vermelho é exatamente o que foi capturado na tela da companhia, veio **SULAMERICA AUTO E MASSIFICADOS** e não **Caixa** .

**Comment by reynaldogoncalves** [comment]
![tela caixa](https://user-images.githubusercontent.com/23550790/28466605-57df68ec-6e03-11e7-9861-b9ff85a85106.PNG)


Na tela da CIA esta como CAIXA
