### ISSUE TITLE
Sistema aceitando placa de formas diferente 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#319]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Campo placas

- O que ocorreu?
O sistema aceitou a placa de duas formas conforme imagem, isso prejudica o historico por placas.

- Numero do sinistro
32693717

- Horário da solicitação
14:17:21

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://user-images.githubusercontent.com/23721255/28484186-64fbf308-6e47-11e7-8c73-b105a29f81c6.png)

**Comment by spmarco** [comment]
corrigido, estará na proxima versão do NASA
