### ISSUE TITLE
Erro ao notificar 

### ISSUE THREAD

**Issue by alanoliveira158420** [JZResgate/NASA-Issues#32]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Atendimento em curso

- O que ocorreu?
Motorista aceitou mais mostra que foi aceito por outro prestador.

- Numero do sinistro
WO0000002544089

- Horário da solicitação
10:47

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/23521390/20524770/369e64f8-b0a3-11e6-81b7-e88b7096cd3f.png)

**Comment by spmarco** [comment]
Corrigido
