### ISSUE TITLE
Erro ao acessar a assistência  WO0000003423692

### ISSUE THREAD

**Issue by priscila123** [JZResgate/NASA-Issues#320]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Atendimento* Histórico atendimento

- O que ocorreu?
Ao acessar a assistência no botão detalhes a pagina dá erro.

- Numero do sinistro
WO0000003423692

- Horário da solicitação
25/07/2017 as 09:02

- Print da tela
![image](https://user-images.githubusercontent.com/25300406/28571191-1af5dd68-7118-11e7-96c4-f264d9825de8.png)

**Comment by brunohbrito** [comment]
Resolvido
