### ISSUE TITLE
Erro na tela de Frota status Consolidado

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#33]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de Status da Frota Consolidado 

- O que ocorreu?
Não esta trazendo retroativo

- Numero do sinistro

- Horário da solicitação

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/20598850/40c45c18-b232-11e6-928f-c74254ae4b37.png)

**Comment by bhdebrito** [comment]
Em analise. 

__Movido para "A fazer"__

**Comment by bhdebrito** [comment]
Tela redesenhada para contemplar os novos status de guincho e retirado os que não são mais utilizados.

Corrigido
