### ISSUE TITLE
Problema na tela de Escala

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#34]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Na tela de Escala - Consultar Escala.

- O que ocorreu?
As viaturas estão repetindo varias vezes.

- Numero do sinistro

- Horário da solicitação

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/20599165/da5d3506-b233-11e6-9a14-efa819da3c5f.png)

**Comment by spmarco** [comment]
Corrigido e já disponível no NASA
