### ISSUE TITLE
[MELHORIA] Impressão de relatorio de serviços fechados dos prestadores. 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#35]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela http://apps.jzresgate.com.br/NASA/Demonstrativo/Pagamentos

- O que ocorreu?
Quando clicamos para imprimir o relatorio de qualquer prestador o sistema esta trazendo diversas placas que não fazem parte do prestador selecionado poluindo o relatorio e gastando mais de 500 folhas de impressão que não servem para mais nada, **prejuizo**.

- Numero do sinistro

- Horário da solicitação
- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/20633185/02547a40-b32b-11e6-9c91-44954fc9ce7e.png)

**Comment by bhdebrito** [comment]
Esse relatorio foi desenvolvido com uma integração ao sistema legado, precisa de uma melhoria para contemplar apenas os serviços do sistema atual

**Comment by bhdebrito** [comment]
Alterado
