### ISSUE TITLE
[MELHORIA] Tela de comparar resultados com campos em branco = 0,00%

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#36]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/NASA/Escala/Comparar

- O que ocorreu?
Na tela de comparar resultados os campos Acionado, No Local e Pericia, ficam zerados, precisamos dos tempos reais.
Arrumar a quantidade de atendimentos com o volume real.

- Numero do sinistro

- Horário da solicitação

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/20633320/5751a242-b32c-11e6-8712-b02f90efc67c.png)

**Comment by bhdebrito** [comment]
Essa tela foi desenvolvida com base nos Status entre o sistema legado e o atual, com a saida do legado essa tela precisa ser refatorada.

**Comment by bhdebrito** [comment]
Alterado.
