### ISSUE TITLE
[MELHORIA] Analise de status não traz acionado e no local, mostra como inativo.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#37]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*http://apps.jzresgate.com.br/NASA/Escala/Analise?placa=EFU-1570&de=01%2F11%2F2016&ate=30%2F11%2F2016

- O que ocorreu?
O NASA não esta trazendo as informações de acionado e no local, quando esta em atendimento o sistema mostra inativo.

- Numero do sinistro

- Horário da solicitação

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/20633374/f542fe10-b32c-11e6-9482-98feb8bc160d.png)

**Comment by bhdebrito** [comment]
Não tem mais os Status Acionado e No Local para o Guincho. Esses Status são do Serviço.

Essa tela precisa ser refeita, pois ainda não contempla as informações do Nasa, ela foi feita na época em que exisita apenas o ASA

**Comment by bhdebrito** [comment]
Alterado.
