### ISSUE TITLE
Não estamos conseguindo liberar em MASSA na Mondial, sem essa função o faturamento despenca.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#38]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/NASA/Frota/AlteracaoEmMassaDadosOperacionais
- O que ocorreu?
A função liberar em MASSA GPS Mondial não esta funcionando, ao conferirmos na tela da Mondial as viaturas não liberam.

- Numero do sinistro

- Horário da solicitação

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/20633580/6bea0bec-b32f-11e6-8e9f-145816aaddbe.png)

**Comment by bhdebrito** [comment]
Modificado a tela.

**Comment by bhdebrito** [comment]
Conforme relatado pelo @MarceloMelloJZ por outro canal, o problema está na integração e não no site Nasa.

Está em desenvolvimento a solução.

**Comment by bhdebrito** [comment]
@MarceloMelloJZ, pedimos por favor, mais uma vez, que sempre que houver atualizações de senha, nos manter informados.

Dentre alguns problemas que houveram um deles foi a senha atualizada sem reportar o T.I.

Corrigido
