### ISSUE TITLE
[DUVIDA] Não conseguimos puxar o retroativo das viaturas por data e hora.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#39]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/NASA/Frota/StatusFrotaConsolidado

- O que ocorreu?
Tela modificada, continuamos sem a opcão de puxar o retroativo.

- Numero do sinistro

- Horário da solicitação
- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/20673858/d6f19776-b56d-11e6-970c-c4a00a884902.png)

**Comment by bhdebrito** [comment]
Existe um botão que permite puxar o retroativo:

![image](https://cloud.githubusercontent.com/assets/7241156/20716592/ea5fc914-b639-11e6-9f76-ee7b55593b23.png)


**Usuários Mac: esse botão não está aparecendo corretamente, em breve haverá um update.**

**Comment by bhdebrito** [comment]
Alterado para Mac.
