### ISSUE TITLE
Erro de Previsão Mapfre

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#40]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Todos os serviços da Mapfre estão caindo na tela com previsão de 2 a 3 horas, após o ultimo erro que os serviços não estavam caindo na captura, antes todos os serviços caiam com a previsão correta de 30 min

- Numero do sinistro
*Ex: 8805954372

- Horário da solicitação
*10:32hs

**Comment by bhdebrito** [comment]
Alterado.
