### ISSUE TITLE
Serviço travado na Captura

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#41]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Serviço travado na captura, o mesmo ja foi exportado e retorna para captura como se não estivesse sido incluido no sistema. 

- Numero do sinistro
*8805957803

- Horário da solicitação
* 11:41hs

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by bhdebrito** [comment]
Serviço estava em teste.
