### ISSUE TITLE
Serviços não estão caindo na Captura Mondial e Europ

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#42]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Serviços não estão caindo na Captura Mondial e Europ

- Numero do sinistro
*Ex: 31262396

- Horário da solicitação
12:12

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by spmarco** [comment]
Resolvido.
#closed

Em qua, 30 de nov de 2016 12:12, Maramoret <notifications@github.com>
escreveu:

**Comment by spmarco** [comment]
Closed #42

Em qua, 30 de nov de 2016 13:46, Marco Aurelio <spmarco@gmail.com> escreveu:
