### ISSUE TITLE
Problema na impressão dos relatorios dos prestadores, 600 folhas mes de prejuizo. 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#43]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/NASA/Demonstrativo/Pagamentos
http://apps.jzresgate.com.br/NASA/Financeiro/ImpressaoIndividual?carimbo=a9e6a719-be68-41ba-b0fd-1ea8eff6a453

- O que ocorreu?
Ao clicarmos no icone de impressão do prestador o sistema esta trazendo no relatorio diversas placas que não é do prestador, isso acontece em todos os prestadores, temos um prejuizo com impressão de 600 folhas todos os meses, pois não é possivel editar a impressão.

- Numero do sinistro

- Horário da solicitação
- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/20795949/ff88e870-b7ba-11e6-9597-47cbcbdefbf3.png)
![image](https://cloud.githubusercontent.com/assets/23721255/20795952/03125dbe-b7bb-11e6-9952-43b17a68592a.png)
![image](https://cloud.githubusercontent.com/assets/23721255/20795961/09210610-b7bb-11e6-94cd-41b922a56fb1.png)
![image](https://cloud.githubusercontent.com/assets/23721255/20795962/0c673f9c-b7bb-11e6-9627-6134d1b3e0e6.png)

**Comment by bhdebrito** [comment]
Já temos um caso em aberto sobre isso #35 

Obrigado por relatar.
