### ISSUE TITLE
[MELHORIA] Notificação e visualização 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#44]
Certifique-se de responder a estas perguntas:

-Melhoria
http://apps.jzresgate.com.br/NASA/Atendimento/AtendimentosEmCurso/PendenteAcionamento

-O que sugere ?
Nessa tela o sistema mostra as 5 melhores opções, sugerimos que as opções apareçam com as cores do status que a mesma esta naquele momento, exemplo: Verde - livre, Amarelo acionado, Roxo no destino e outros status do atendimento e das viaturas.
Notificar as viaturas clicando em cima dos icones ( 5 viaturas que o NASA sugeriu ).
Notificar somente com 1 clique. 

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/20804223/354983c0-b7d9-11e6-83d6-a3d450d4294a.png)

**Comment by brunohbrito** [comment]
Essa melhoria será congelada, pois para efetuar os calculos, precisamos de uma licença do Google.

Para nosso volume de atendimentos, consultamos o Google em média 100k ao dia. Com uma licença Free, temos apenas 2,5k de consultas.
