### ISSUE TITLE
Nasa do Usuario Vitor Felix não esta Capturando

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#45]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Todas as assistências que são aceitas nas paginas da CIA não estão caindo na Capturado do NASA do analista Vitor Felix, somente o usuario dele esta com esse problema.

- Numero do sinistro
*Ex:31273314

- Horário da solicitação
*08:14

**Comment by bhdebrito** [comment]
Resolvido
