### ISSUE TITLE
Problemas na Captura dos serviços da BB Mapfre

### ISSUE THREAD

**Issue by JZMARRUDA** [JZResgate/NASA-Issues#46]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento, Captura.

- O que ocorreu?
*Os serviços da BB Mapfre estão sendo aceitos na pagina e não estão aparecendo na Captura.

- Numero do sinistro
*Ex: 8805964112 // 8805964090

- Horário da solicitação
* 8805964090 ACEITO 02/12/2016 às 16:00:36
* 8805964112 ACEITO 02/12/2016 às 16:10:01

- Print da tela
*Os serviços não apareceram na captura e foram exportados manualmente, não sendo possível possivel tirar um print desse problema.

**Comment by bhdebrito** [comment]
@JZMARRUDA,

A captura apresentou uma instabilidade, porem já está capturando normalmente. 

* **8805964112**: Não há registros de captura desse sinistro
* **8805964090**: Exportado manualmente, há registros dele no sistema.
