### ISSUE TITLE
Problemas com agendamento 

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#47]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Os serviços agendados não estão caindo no pendente acionamento.

- Numero do sinistro
*Ex:  WO0000002591964/502508/502516

- Horário da solicitação
*16:00

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by bhdebrito** [comment]
@Maramoret, obrigado por relatar.

O problema resolvido.
