### ISSUE TITLE
Lançamento de placas com - ou não.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#48]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
No cadastro de placas

- O que ocorreu?
O sistema aceita que seja lançado placas com  ( - )  ou sem ( - ) 
Exemplo - FTG0328 // FTG-0328
- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/20901147/5699799e-bb18-11e6-8021-c65c8669c49b.png)

**Comment by bhdebrito** [comment]
Sera alterado na próxima versao
