### ISSUE TITLE
Viatura GJZ 103 FHJ0459 travada em atendimento.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#49]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Status da viatura 

- O que ocorreu?
A viatura ficou travada em atendimento 

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/20919886/06d688ee-bb85-11e6-922f-a3ab3a180f34.png)

**Comment by bhdebrito** [comment]
Frotas em pontinhos é porque algum usuário **acionou** a frota para um serviço Agendado, utilizando os acessos do Financeiro.

Conforme detalhado no erro #29
