### ISSUE TITLE
Viatura GJZ 098 FFN 7669 ficou travada em atendimento 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#50]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Status da viatura 

- O que ocorreu?
A viatura GJZ 098 FFN7669 travou em atendimento.
- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/20919931/3a259d70-bb85-11e6-8732-ee315a87a049.png)

**Comment by bhdebrito** [comment]
Frotas em pontinhos é porque algum usuário **acionou** a frota para um serviço Agendado, utilizando os acessos do Financeiro.

Conforme detalhado no erro #29
