### ISSUE TITLE
Prestador aceita atendimento mas  atendimento ainda fica como reservado.

### ISSUE THREAD

**Issue by Sidnei4P** [JZResgate/NASA-Issues#51]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?

**Na tela de atendimento em curso**

- O que ocorreu?

Prestador aceitou o serviço via notificação mais atendimento ainda continua no NASA como reservado.
Como vocês pode ver no print abaixo , no Nasa temos a confirmação que fui aceita pelo prestador no campo de Notificação.

- Numero do sinistro
 JZ2016125152412 ( Remoção 02)

- Horário da solicitação
 05/12/2016 AS 08:26

- Print da tela

![image](https://cloud.githubusercontent.com/assets/23553257/20922432/4247bbb4-bb8f-11e6-9995-203a8a104335.png)

![image](https://cloud.githubusercontent.com/assets/23553257/20922462/5cb2368c-bb8f-11e6-8423-2623095bc4ee.png)
![image](https://cloud.githubusercontent.com/assets/23553257/20922468/6444ae3e-bb8f-11e6-9954-744e29e5d022.png)

*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by bhdebrito** [comment]
Olá @Sidnei4P, obrigado por relatar.

Analisamos o ocorrido.

As duas notificações do print de Tela estão vinculadas ao Serviço _1 - Remoção_.

A notificação do Serviço *2 - Remoção* foi criado às *08:39:50*

Log dos Eventos:
* Notificação Enviada às *08:39:50*
* Notificação Recebida pelo Celular às *08:39:53*
* Confirmação de Leitura do Motorista às *08:39:54*
* Resposta da Notificação recebida pelo nosso servidor às *08:40:01*

**Comment by Sidnei4P** [comment]
Senhores se aconteceu isso temos outro erro, não podemos ter um atendimento aceito por dois prestadores.

**Comment by bhdebrito** [comment]
A nova versão liberada houve uma modificação para prefinir situações como esta. Caso ocorra novamente, por favor sinalize.

Obrigado.
