### ISSUE TITLE
[MELHORIA] ( Criar o perfil de  frota Pesado leve ) os trucadinhos

### ISSUE THREAD

**Issue by Sidnei4P** [JZResgate/NASA-Issues#52]
Certifique-se de responder a estas perguntas:

Todos analistas do Pesado precisam  visualizar as frotas trucadinhos ( caminhões que são usados tanto no seguimento de leves , como  nos  atendimento de pesado )
Precisamos que seja criado este seguimento, ha  partir  de janeiro de 2017 nos pesado na intenção de aumentar a produtividade das frotas 201,202,203,204 iremos ajudar  a gerenciar esta frotas mais para isso precisamos desta ferramenta.

![image](https://cloud.githubusercontent.com/assets/23553257/20922931/2391b2cc-bb91-11e6-9123-d293944c04d9.png)

![image](https://cloud.githubusercontent.com/assets/23553257/20923013/93d670cc-bb91-11e6-8da4-7783b4e887e3.png)

**Comment by brunohbrito** [comment]
@Sidnei4P Com a nova tela de Geoposicionamento estamos colocando filtros por tipo de guincho. Na próxima versao tera a opcao de selecionar o tipo de guinche trucadinho.
