### ISSUE TITLE
Valor zerado

### ISSUE THREAD

**Issue by Sidnei4P** [JZResgate/NASA-Issues#53]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?

1.  **# Atendimento em Curso/ detalhe do serviço**

- O que ocorreu?
 `

> atendimento criado e lançado o valor o valor de R$ 850,00 apos salvas as informações o atendimento aparece com valor zerado conforme print abaixo.

`
- Numero do sinistro
 

> OS5245433

- Horário da solicitação

> #  06/12/2016 as 14:14

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23553257/20933462/3fbf32de-bbbf-11e6-870e-578f653c0d33.png)

**Comment by bhdebrito** [comment]
Corrigido e entrará na próxima versao.
