### ISSUE TITLE
Acionamento - Sem nome do motorista

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#54]
Bruno, boa tarde!

Identificamos um problema no fechamento dos atendimentos NASA. Muitos casos não constam acionamentos de frota e motorista.

Pelos analisados já identificamos mais de 80 casos.

Abaixo alguns exemplos:

31284878
31289009
31289404
31276764
31287490
31284956
31287542
31286146
31286024
31284847
31285228
31285749
31286583
31285205
31286321
31285282
31284249
31285971
31286755
31286831
31288373
WO0000002586375 - Sem motorista acionado e sem histórico de acionamento
WO0000002587931 - Sem motorista acionado, porém com histórico de acionamento
WO0000002586397 - Sem motorista acionado e sem histórico de acionamento
WO0000002588328 - Sem motorista acionado, porém com histórico de acionamento
WO0000002586088 - Sem motorista acionado, porém com histórico de acionamento
WO0000002589507 - Sem motorista acionado, porém com histórico de acionamento
WO0000002592316 - Sem motorista acionado e sem histórico de acionamento
WO0000002585630 -  Sem motorista acionado, porém com histórico de acionamento
WO0000002584960 - Sem motorista acionado e sem histórico de acionamento
WO0000002583886 - Sem motorista acionado e sem histórico de acionamento

**Comment by JZWillian** [comment]
Se fecharmos e faturarmos os atendimentos não será possível a edição do mesmo e neste caso eles não irão gerar comissão.

**Comment by bhdebrito** [comment]
Corrigido
