### ISSUE TITLE
Erro Nasa Frota em Pontinho e Serviços com Status concluido

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#55]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento,

- O que ocorreu?
*Serviços acionado frota GJZ 141 Ficou travada em pontinho e no Status da assistência esta como concluida, porém motorista está seguindo para local.

- Numero do sinistro
*Ex: 503799

- Horário da solicitação
* 15:28

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

![Uploading image.png…]()

**Comment by bhdebrito** [comment]
@Maramoret, não conseguimos reproduzir ou avaliar o problema.

Consegue nos dizer passo a passo o que ocorreu?

**Comment by bhdebrito** [comment]
Sem Resposta.

Closed
