### ISSUE TITLE
Alteração "Status NASA" Mondial não funcionando

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#56]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASA - tela de alteração em MASSA

- O que ocorreu?
Quando optamos por alteração em MASSA para "Status NASA" percebemos que o sistema não acata a ação

- Numero do sinistro

- Horário da solicitação
Tentamos realizar nesse momento a alteração sem sucesso (08/12 as 10:10

- Print da tela

**Comment by bhdebrito** [comment]
@reynaldogoncalves,

Efetuamos testes, conforme indicado e não apresentou esse problema:

Ocupando:
![image](https://cloud.githubusercontent.com/assets/7241156/21011337/eef68abc-bd37-11e6-9296-67eb5c30d315.png)

Liberando:
![image](https://cloud.githubusercontent.com/assets/7241156/21011403/2c44500c-bd38-11e6-98f9-0e6bdc6dd646.png)
