### ISSUE TITLE
Mondial não esta Capturando

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#57]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Mondial não esta caindo na captura

- Numero do sinistro
*Ex: 31314403 e 31314111

- Horário da solicitação
*12:16hs

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by bhdebrito** [comment]
Problema do webservice resolvido
