### ISSUE TITLE
DOIS PRESTADORES ACEITOU O MESMO SERVIÇO 

### ISSUE THREAD

**Issue by alanoliveira158420** [JZResgate/NASA-Issues#58]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela do atendimento 

- O que ocorreu?
Foi notificado duas viaturas e as duas conseguiu aceitar o serviço 

- Numero do sinistro
WO0000002603481

- Horário da solicitação
12:19

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23521390/21013682/2ee6e00e-bd42-11e6-87bc-158046f175bc.png)

**Comment by spmarco** [comment]
Em andamento

**Comment by bhdebrito** [comment]
Alterado nesta versao.
