### ISSUE TITLE
O status Particular não aparece no Status Consolidado

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#61]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/NASA/Frota/StatusFrotaConsolidado

- O que ocorreu?
As viaturas em status particular não aparecem no Status Consolidado.

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/21196447/c84fcf7c-c21e-11e6-9a16-cf7f5b631e59.png)

**Comment by bhdebrito** [comment]
Alterado.

Estará disponível na próxima versao
