### ISSUE TITLE
Não esta gerando lote sinistro JZ201611231532 

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#62]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
http://apps.jzresgate.com.br/NASA/Atendimento/Historico/Detalhes?id=JZ201611231532&servico=1

- O que ocorreu?
Não estamos conseguindo gerar lote do atendimento

- Numero do sinistro
JZ201611231532 

- Horário da solicitação
19/12/2016  10:50  login Willian Nascimento

- Print da tela

![image](https://cloud.githubusercontent.com/assets/24438478/21313481/3d4eae2a-c5d9-11e6-8986-4171a687183b.png)

**Comment by JZWillian** [comment]
bom dia!
como acompanho previsão?

**Comment by bhdebrito** [comment]
Ainda não houve avaliação, por isso não tem previsão.

**Comment by JZWillian** [comment]
Depois preciso entender como funciona para não ficar cobrando toda hora.

**Comment by bhdebrito** [comment]
Resolvido, por favor verifique novamente

**Comment by bhdebrito** [comment]
Sem resposta
