### ISSUE TITLE
Atendimentos Mondial "pendente acionamento"

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#63]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASA TELA DE ABERTOS 

- O que ocorreu?

Conforme falamos pela manhã os atendimentos da Mondial que são criados através de algum outro finalizado ou cancelado estão ficando fora de ordem na parte de acionamento.

Por algum motivo eles não ficam na ordem de acionamento e acabam se "isolando" dos demais, onde corremos o risco de não vê-los.

Após acionados o motorista fica em "pontinho", sempre temos que cancelar o acionamento e acionar novamente.

- Numero do sinistro
*Ex: 31373603

- Horário da solicitação
13:20

- Print da tela
DIRECIONADO POR EMAIL

**Comment by bhdebrito** [comment]
Modificados para a próxima versao
