### ISSUE TITLE
http://apps.jzresgate.com.br/NASA/Escala/Comparar

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#64]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Na tela de comparar jornada 

- O que ocorreu?
Como melhoria precisamos conseguir ordenar por tipo as colunas. 

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/21329892/3fa163e0-c622-11e6-8780-92ceed9101bd.png)

**Comment by bhdebrito** [comment]
Estará disponível na próxima versao
