### ISSUE TITLE
Melhoria para o sistema não gerar comissão para Pedagios e Estadias de Patio 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#65]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Quando gera a comissão para os prestadores.

- O que ocorreu?
O sistema gera a comissão para pagamento de pedagios e estadias de patio, esses tipos de serviço não são pagos em hipotese alguma.

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/21365439/7f8afc9a-c6dc-11e6-874f-bfcc6e4209b6.png)

**Comment by brunohbrito** [comment]
Estará disponivel na próxima versao.
