### ISSUE TITLE
Problemas NO APP

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#66]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Aplicativo 
- O que ocorreu?
Os motoristas não estão conseguindo se logar.
Alguns logados ( minoria ) diz não estar recebendo as notificações
Outros não estão conseguindo abrir o APP.

**Comment by spmarco** [comment]
Corrigido
