### ISSUE TITLE
Serviço travado na Captura

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#67]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Serviços travado na Captura, já foi fechado no X diversas vezes mais ele retorna

- Numero do sinistro
*Ex:9075152 Brasil Assistência

- Horário da solicitação
*12:45hs

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by bhdebrito** [comment]
Já está ok
