### ISSUE TITLE
Lentidão na Captura das CIAS

### ISSUE THREAD

**Issue by Maramoret** [JZResgate/NASA-Issues#68]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento

- O que ocorreu?
*Estamos com lentidão na Captura dos Serviços, esta demorando em média 2 min para cair para exportação

- Numero do sinistro
*Ex: 31414891

- Horário da solicitação
*08:39hs caiu na captura as 08:41hs

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by bhdebrito** [comment]
Lentidão na captura é um problema em geral com a lentidão de alguma pagina de CIA, nao temos como interferir nisso.
