### ISSUE TITLE
NASA com Ordem Invertida

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#69]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASA todas as telas

- O que ocorreu?
Prezados,
Bom dia!

Favor verificar pois o NASA está apresentando a ordem as informações invertidas.

Veja conforme abaixo, a pendencia de placa está em ultimo lugar, isso dificulta a ação dos analistas.

- Numero do sinistro
8806052553

- Horário da solicitação
07:40

- Print da tela

**Comment by bhdebrito** [comment]
Obrigado pele feedback. Problema resolvido!
