### ISSUE TITLE
Pedágio - incluir colunas bairros 

### ISSUE THREAD

**Issue by JZWillian** [JZResgate/NASA-Issues#71]
Certifique-se de responder a estas perguntas:

solicitamos a inclusão de colunas Região na planilha de pedágio.

hoje a mesma inclui a informação apenas de percurso e precisamos ajustar para que fique apenas os bairros ou cidades de origem e destino.

![image](https://cloud.githubusercontent.com/assets/24438478/21589926/09b5eadc-d0de-11e6-8a0b-4c9169fbae08.png)

**Comment by JZWillian** [comment]
se precisar entender melhor me avisa.
valeu.

**Comment by JZWillian** [comment]
Boa tarde !

Bruno, alguma novidade?
valeu

**Comment by brunohbrito** [comment]
Nao.

**Comment by brunohbrito** [comment]
Alterado. Os proximos arquivos terao essa informacao.
