### ISSUE TITLE
NASA duplica endereço de destino

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#72]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela do NASA - Alteração de Percurso

- O que ocorreu?
Quando colocamos um endereço de destino o NASA automaticamente insere uns 30 endereços iguais, e temos que retirar manualmente , travando o sistema

- Numero do sinistro
8806056311

- Horário da solicitação
15:25

- Print da tela

**Comment by spmarco** [comment]
Correção feita e será disponibilizada na próxima publicação do NASA
