### ISSUE TITLE
Melhoria em relatorios - Serviços por Região - Bairro e Tipo de Serviços

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#73]
Certifique-se de responder a estas perguntas:

- Aonde é a melhoria ?
Relatorio e Historico de serviços. 

- O que ocorreu?
Precisamos analisar serviços por Regiões e Bairros em relatorios e historico de serviços por clientes, viaturas, motoristas e por horario de acionamento.
Precisamos também ( muito importante ) filtrar esses relatorios por tipo de serviços.

**Comment by spmarco** [comment]
Feito e disponivel na tela de Relatorio/Servico/PorAcionamento
