### ISSUE TITLE
Melhoria na tela liberação em Massa GPS.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#77]
Certifique-se de responder a estas perguntas:

- Aonde é a melhoria ?
http://apps.jzresgate.com.br/NASA/Frota/AlteracaoEmMassaDadosOperacionais

- Qual é a melhoria ?
Criar raio para liberar automaticamente a viatura que esta indo para o destino.
Campo com a KM para preenchermos com a quantidade de KM que determinarmos por viatura.
Liberação em MASSA por região, exemplo: Leste 1, Norte 2, Sul 3 etc.
Opção de liberar as viaturas que estão a X KM da viatura livre, exemplo: Viatura GMOD 021 liberado na Av Paulista, em um raio de X KM liberaria automaticamente todas ao redor dessa.

**Comment by brunohbrito** [comment]
Em produçao.
