### ISSUE TITLE
Melhoria na tela de serviços Agendados.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#79]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu a melhoria?
http://apps.jzresgate.com.br/NASA/Atendimento/Servico/Agendados

- O que sugere ?
Precisamos que a tela seja atualizada para visualização igual do atendimento em curso, com as colunas iguais.
Criar reserva de agendamento.
Criar icone e status Reserva de Agendamento.
Conseguir acionar a reserva de agendamento.

**Comment by brunohbrito** [comment]
#238
