### ISSUE TITLE
erro 

### ISSUE THREAD

**Issue by ricardomellojz** [JZResgate/NASA-Issues#8]
mudança de horario

![image](https://cloud.githubusercontent.com/assets/23509659/20386105/41d47494-aca1-11e6-8e60-5a61b610cc1e.png)

**Comment by bhdebrito** [comment]
Precisamos do numero do sinistro para poder efetuar testes. 

Com outros atendimentos é possivel agendar normalmente.

**Comment by bhdebrito** [comment]
Corrigido.
