### ISSUE TITLE
Melhoria na TELA Geoposição

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#80]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu a melhoria?
http://apps.jzresgate.com.br/NASA/Frota/Geoposicao

- O que sugere ?
Melhorar a visualização dos icones com as cores dos Status reais.
Visualização por cliente e status.
Historico com a visualização das viaturas com as cores e status reais no periodo.
Aumentar a tela do Mapa que só usa uns 80% da tela, na parte de baixo não desce até o fim.

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/21609242/69536030-d1a8-11e6-8384-d740d0072e0e.png)

**Comment by brunohbrito** [comment]
Nova versao no ar
