### ISSUE TITLE
Erro na visualição do serviço 

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#81]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela  Historico

- O que ocorreu?
*Ao clicar para abrir a tela, não consigo visualizar os dados do atendimento

- Numero do sinistro
30584627

- Horário da solicitação
11:35hs 
- Print da tela

![image](https://cloud.githubusercontent.com/assets/24894704/21609316/dd498f96-d1a8-11e6-9aba-f48fb9060471.png)

**Comment by bhdebrito** [comment]
Resolvido
