### ISSUE TITLE
Criação de um relatorio detalhado por viatura e motorista - DESEMPENHO. 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#82]
Certifique-se de responder a estas perguntas:

Criar um relatorio conforme email enviado ( excel ).
Desempenho com todos os indicadores de recusas, tempo, KM e etc.

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/21610310/57c44040-d1ae-11e6-9ed5-1d4a2de13399.png)

**Comment by brunohbrito** [comment]
Nao é ideal na mesma tela ter as duas informações de Motorista e por Viatura, o ideal é ter duas telas.

No caso de Motoristas nao temos o controle de horas em Op . Fora de Op. essa informação é intrínseca ao guincho.

**Comment by brunohbrito** [comment]
Entregue a primeira versao
