### ISSUE TITLE
Melhoria na tela do Mapa - Rota cliente e destino.

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#83]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Quando abrimos o MAPA do atendimento no status pendente de acionamento, a visualização da rota via google do cliente e destino é marcada com os icones de uma bandeira e de um carro no local da remocão e no destino marcado na rota em vermelho.
Apos o acionamento, no status em andamento e concluido os icones somem focando apenas a rota em vermelho.
- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/21641475/358658b4-d263-11e6-9a12-3cc8bb0b02ea.png)

![image](https://cloud.githubusercontent.com/assets/23721255/21641477/38d6eaf6-d263-11e6-8139-577184ced195.png)

**Comment by brunohbrito** [comment]
Melhoria será disponibilizada na próxima versao.

**Comment by spmarco** [comment]
Correção disponibilizada
