### ISSUE TITLE
Exportar Brasil Assistencia 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#84]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Exportar atendimentos.

- O que ocorreu?
A Brasil Assistencia alterou o sistema enviando somente o numero de sinistro, o ME é enviado somente apos a baixa da placa.
- Sugestão ?
Precisamos exportar via numero de sinistro, pois manualmente gera muito tempo.

**Comment by brunohbrito** [comment]
Em progresso
