### ISSUE TITLE
Frota não Vincula Apos Acionamento

### ISSUE THREAD

**Issue by reynaldogoncalves** [JZResgate/NASA-Issues#86]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
NASA tela de acionamento

- O que ocorreu?
As assistências não estão vinculando no prestador, quando notificados e não aceitos e acionamos o motorista diretamente não vincula a frota dele. temos que ir no sistema caminhões e vincular manualmente

- Numero do sinistro
21fpfs/30

- Horário da solicitação
09:33

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by bhdebrito** [comment]
Iremos analisar o quanto antes.

**Comment by bhdebrito** [comment]
#142
