### ISSUE TITLE
Melhoria na tela de historico

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#87]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu a melhoria ?
http://apps.jzresgate.com.br/NASA/Atendimento/Historico/Servicos

- O que sugere?
Precisamos puxar nos relatorios os itens Região, veiculo e tipo de reboque ( leve, utilitario, pesado, patins, rodas, etc...)

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/21681207/65f123da-d335-11e6-8033-3252a65eb95c.png)

**Comment by brunohbrito** [comment]
Alterado os filtros, unificando aos poucos todas as telas com as mesmas opçoes de filtro.
