### ISSUE TITLE
Melhoria na tela de comparar 

### ISSUE THREAD

**Issue by MarceloMelloJZ** [JZResgate/NASA-Issues#88]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu a melhoria?
http://apps.jzresgate.com.br/NASA/Escala/Comparar

- O que precisa ?
Precisamos clicar e ordenar as colunas.

- Print da tela
![image](https://cloud.githubusercontent.com/assets/23721255/21681255/9ec8ac8c-d335-11e6-9f6b-2fd86a940d63.png)

**Comment by bhdebrito** [comment]
Ja há uma solicitacao dessa. #64
