### ISSUE TITLE
Consulta por placas com deficiência

### ISSUE THREAD

**Issue by gilsonlirio** [JZResgate/NASA-Issues#89]
Temos percebido que em alguns casos não é possível concluir a consulta por placa.

Algumas placas: NWF-4793, OQZ-5301, NSH-3392
Quando consultamos pelo sinistro, obtemos sucesso.

No aguardo

**Comment by spmarco** [comment]
vamos verificar

**Comment by bhdebrito** [comment]
Sera modificado na proxima versao
