### ISSUE TITLE
Erro nasa

### ISSUE THREAD

**Issue by emersonmedeiros** [JZResgate/NASA-Issues#9]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Ex: Tela de atendimento, Historico, Relatorio Financeiro

- O que ocorreu?
*Relate com algum nivel de detalhes o que ocorreu, evite descrições genéricas do tipo: Não funciona

- Numero do sinistro
*Ex: 31173208

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows

**Comment by bhdebrito** [comment]
Sem descrição do problema
