### ISSUE TITLE
Dificuldade de consulta por placa com hífen

### ISSUE THREAD

**Issue by gilsonlirio** [JZResgate/NASA-Issues#90]
Temos observado que em algumas placas não conseguimos consultar com êxito.

Ao lançar a placa, não gera resultado no padrão normal.
Temos que retornar onde está o hífen da placa e clicar em "Delete" para então concluir a pesquisa. Quando surge o resultado, percebemos a placa sem hífen.

Aguardo retorno

**Comment by bhdebrito** [comment]
Problema ja relatado. Acompanhe atraves do item #48
