### ISSUE TITLE
Impossibilidade de reativar clientes

### ISSUE THREAD

**Issue by gilsonlirio** [JZResgate/NASA-Issues#91]
Após desativar um cliente, não tenho opção de reativá-lo no Nasa.

Preciso ter essa facilidade, pois às vezes o bloqueio é apenas temporário.

Exemplo: Locamérica, que só conseguimos reativar através da ação da TI.

No aguardo

Gilson Lírio

**Comment by bhdebrito** [comment]
Sera corrigido na próxima versao
