### ISSUE TITLE
CAPTURA SERVIÇOS EUROP

### ISSUE THREAD

**Issue by eliasreis** [JZResgate/NASA-Issues#95]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de atendimento (CAPTURA)

- O que ocorreu?
Serviços da EUROP, não estão caindo no captura.

- Numero do sinistro
  Todas  as WO 

- Horário da solicitação
A partir das 09h30min todos os serviços aceitos da EUROP não estão caindo na tela de captura, estão sendo exportados manualmente.

**Comment by bhdebrito** [comment]
@eliasreis, bom dia
Estamos analisando para corrigir o problema.

**Comment by bhdebrito** [comment]
@eliasreis por favor tente novamente.

**Comment by bhdebrito** [comment]
Fechado sem resposta
