### ISSUE TITLE
Frota não veicula

### ISSUE THREAD

**Issue by alanoliveira158420** [JZResgate/NASA-Issues#96]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Tela de atendimento

- O que ocorreu?
as frotas apos ser acionada não esta veiculado a frota no atendimento

- Horário da solicitação
09:30

![image](https://cloud.githubusercontent.com/assets/23521390/22202742/ae70f40e-e150-11e6-88d6-8026f1f17336.png)

**Comment by bhdebrito** [comment]
@alanoliveira158420, por favor tente novamente!

Bug corrigido.

**Comment by spmarco** [comment]
corrigido
