### ISSUE TITLE
ERRO NASA : "MARCAR COMO ANALISADO" - FECHAMENTO

### ISSUE THREAD

**Issue by Camila123** [JZResgate/NASA-Issues#97]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
Fechamento:
- Atendimento / Histórico / Detalhes
http://apps.jzresgate.com.br/NASA/jz-resgate/Brasil/Atendimento/Historico/Detalhes?id=

- O que ocorreu?
* Botão "MARCAR SERVIÇO COMO ANALISADO": Ao clicarmos no botão aparece uma mensagem dizendo: " ERRO AO EFETUAR A SOLICITAÇÃO.  POR FAVOR VERIFIQUE OS ERROS ABAIXO....

- Numero do sinistro
Todos os atendimentos. Nao estamos conseguindo marcar nenhum atendimento como "analisado'.

- Horário da solicitação
23/01/2017 11:53

- Print da tela

![image](https://cloud.githubusercontent.com/assets/25299834/22206483/a6821252-e162-11e6-85e4-c00bf61d47c5.png)

**Comment by spmarco** [comment]
corrigido
