### ISSUE TITLE
Marcar como Analisado

### ISSUE THREAD

**Issue by Cristianerangel** [JZResgate/NASA-Issues#98]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
*Pagina de consulta " Historico"

- O que ocorreu?
*Não esta marcando como Analisado 

- Numero do sinistro
*31599333
- Horário da solicitação
* entre 12:20 e 12:21

- Print da tela
*Tire print da tela utilizando a "Ferramenta de Captura" do Windows
![image](https://cloud.githubusercontent.com/assets/24894704/22207497/87b20568-e166-11e6-8093-ce73c24f47d0.png)

**Comment by bhdebrito** [comment]
Corrigido.

Tente novamente
