### ISSUE TITLE
FINANCEIRO - ERRO AO GERAR FATURA

### ISSUE THREAD

**Issue by Camila123** [JZResgate/NASA-Issues#99]
Certifique-se de responder a estas perguntas:

- Aonde ocorreu o problema?
fechamento / fatura / pesquisa

- O que ocorreu?
Clicando no "botao" "nova fatura", apresenta tela apresenta erro e não gera nova fatura.

![image](https://cloud.githubusercontent.com/assets/25299834/22210946/9c4d5020-e172-11e6-9535-ea4b1a4591ee.png)

- Numero do sinistro

- Horário da solicitação
21/01/2017 13:45

- Print da tela

![image](https://cloud.githubusercontent.com/assets/25299834/22210936/90274562-e172-11e6-87d0-73d7024f39ea.png)

**Comment by spmarco** [comment]
Corrigido @Camila123
